import{addLocalesMessages as u,Text as o}from"@blockcode/core";var a={en:{"blocks.dht.name":"DHT","blocks.dht.temperature11":"pin [PIN] DHT11 temperature","blocks.dht.humidity11":"pin [PIN] DHT11 humidity","blocks.dht.temperature22":"pin [PIN] DHT22 temperature","blocks.dht.humidity22":"pin [PIN] DHT22 humidity"},"zh-Hans":{"blocks.dht.name":"DHT 温湿度","blocks.dht.temperature11":"引脚[PIN] DHT11 温度","blocks.dht.humidity11":"引脚[PIN] DHT11 湿度","blocks.dht.temperature22":"引脚[PIN] DHT22 温度","blocks.dht.humidity22":"引脚[PIN] DHT22 湿度"},"zh-Hant":{"blocks.dht.name":"DHT 溫濕度","blocks.dht.temperature11":"引腳[PIN] DHT11 溫度","blocks.dht.humidity11":"引腳[PIN] DHT11 濕度","blocks.dht.temperature22":"引腳[PIN] DHT22 溫度","blocks.dht.humidity22":"引腳[PIN] DHT22 濕度"}};var l="./assets/icon-7tetjn1q.svg";import{jsx as r}from"preact/jsx-runtime";var h=(d)=>d.editor==="@blockcode/gui-iotbit";u(a);var P={icon:l,name:r(o,{id:"blocks.dht.name",defaultMessage:"DHT"}),blocks:(d)=>[{id:"temperature11",text:r(o,{id:"blocks.dht.temperature11",defaultMessage:"pin [PIN] DHT11 temperature"}),output:"number",inputs:{PIN:h(d)?{menu:"iotPins"}:{type:"positive_integer",defaultValue:1}},ino(n){let i=this.valueToCode(n,"PIN",this.ORDER_NONE);this.definitions_.include_dht='#include "dht.h"',this.definitions_.variable_dht="dht _dht;";let t="";return t+=`int getTemperature(int pin, bool dht22) {
`,t+=`  dht22 ? _dht.read22(pin) : _dht.read11(pin);
`,t+=`  return _dht.temperature;
`,t+="}",this.definitions_.declare_getTemperature="int getTemperature(int pin, bool dht22 = false);",this.definitions_.getTemperature=t,[`getTemperature(${i})`,this.ORDER_FUNCTION_CALL]},mpy(n){let i=this.valueToCode(n,"PIN",this.ORDER_NONE),t=`pin_${i}`;this.definitions_.import_pin="from machine import Pin",this.definitions_.import_dht11="from dht import DHT11",this.definitions_[t]=`${t} = DHT11(Pin(${i}))`;let e="";return e+=`def get_temperature(dht):
`,e+=`  dht.measure()
`,e+=`  return dht.temperature()
`,this.definitions_.def_get_temperature=e,[`get_temperature(${t})`,this.ORDER_FUNCTION_CALL]}},{id:"humidity11",text:r(o,{id:"blocks.dht.humidity11",defaultMessage:"pin [PIN] DHT11 humidity"}),output:"number",inputs:{PIN:h(d)?{menu:"iotPins"}:{type:"positive_integer",defaultValue:1}},ino(n){let i=this.valueToCode(n,"PIN",this.ORDER_NONE);this.definitions_.include_dht='#include "dht.h"',this.definitions_.variable_dht="dht _dht;";let t="";return t+=`int getHumidity(int pin, bool dht22) {
`,t+=`  dht22 ? _dht.read22(pin) : _dht.read11(pin);
`,t+=`  return _dht.humidity;
`,t+="}",this.definitions_.declare_getHumidity="int getHumidity(int pin, bool dht22 = false);",this.definitions_.getHumidity=t,[`getHumidity(${i})`,this.ORDER_FUNCTION_CALL]},mpy(n){let i=this.valueToCode(n,"PIN",this.ORDER_NONE),t=`pin_${i}`;this.definitions_.import_pin="from machine import Pin",this.definitions_.import_dht11="from dht import DHT11",this.definitions_[t]=`${t} = DHT11(Pin(${i}))`;let e="";return e+=`def get_humidity(dht):
`,e+=`  dht.measure()
`,e+=`  return dht.humidity()
`,this.definitions_.def_get_humidity=e,[`get_humidity(${t})`,this.ORDER_FUNCTION_CALL]}},"---",{id:"temperature22",text:r(o,{id:"blocks.dht.temperature22",defaultMessage:"pin [PIN] DHT22 temperature"}),output:"number",inputs:{PIN:h(d)?{menu:"iotPins"}:{type:"positive_integer",defaultValue:1}},ino(n){let i=this.valueToCode(n,"PIN",this.ORDER_NONE);this.definitions_.include_dht='#include "dht.h"',this.definitions_.variable_dht="dht _dht;";let t="";return t+=`int getTemperature(int pin, bool dht22) {
`,t+=`  dht22 ? _dht.read22(pin) : _dht.read11(pin);
`,t+=`  return _dht.temperature;
`,t+="}",this.definitions_.declare_getTemperature="int getTemperature(int pin, bool dht22 = false);",this.definitions_.getTemperature=t,[`getTemperature(${i}, true)`,this.ORDER_FUNCTION_CALL]},mpy(n){let i=this.valueToCode(n,"PIN",this.ORDER_NONE),t=`pin_${i}`;this.definitions_.import_pin="from machine import Pin",this.definitions_.import_dht22="from dht import DHT22",this.definitions_[t]=`${t} = DHT22(Pin(${i}))`;let e="";return e+=`def get_temperature(dht):
`,e+=`  dht.measure()
`,e+=`  return dht.temperature()
`,this.definitions_.def_get_temperature=e,[`get_temperature(${t})`,this.ORDER_FUNCTION_CALL]}},{id:"humidity22",text:r(o,{id:"blocks.dht.humidity22",defaultMessage:"pin [PIN] DHT22 humidity"}),output:"number",inputs:{PIN:h(d)?{menu:"iotPins"}:{type:"positive_integer",defaultValue:1}},ino(n){let i=this.valueToCode(n,"PIN",this.ORDER_NONE);this.definitions_.include_dht='#include "dht.h"',this.definitions_.variable_dht="dht _dht;";let t="";return t+=`int getHumidity(int pin, bool dht22) {
`,t+=`  dht22 ? _dht.read22(pin) : _dht.read11(pin);
`,t+=`  return _dht.humidity;
`,t+="}",this.definitions_.declare_getHumidity="int getHumidity(int pin, bool dht22 = false);",this.definitions_.getHumidity=t,[`getHumidity(${i}, true)`,this.ORDER_FUNCTION_CALL]},mpy(n){let i=this.valueToCode(n,"PIN",this.ORDER_NONE),t=`pin_${i}`;this.definitions_.import_pin="from machine import Pin",this.definitions_.import_dht22="from dht import DHT22",this.definitions_[t]=`${t} = DHT22(Pin(${i}))`;let e="";return e+=`def get_humidity(dht):
`,e+=`  dht.measure()
`,e+=`  return dht.humidity()
`,this.definitions_.def_get_humidity=e,[`get_humidity(${t})`,this.ORDER_FUNCTION_CALL]}}],menus:{iotPins:{items:[["P0","33"],["P1","32"],["P2","35"],["P3","34"],["P4","39"],["P5","0"],["P6","16"],["P7","17"],["P8","26"],["P9","25"],["P10","36"],["P11","2"],["P13","18"],["P14","19"],["P15","21"],["P16","5"],["P19","22"],["P20","23"],["P23","27"],["P24","14"],["P25","12"],["P26","13"],["P27","15"],["P28","4"]]}}};export{P as default};
