import{addLocalesMessages as T,Text as g}from"@blockcode/core";import{Text as n}from"@blockcode/core";import{jsx as d}from"preact/jsx-runtime";var f=(s)=>[{id:"initReceive",text:d(n,{id:"blocks.infraredcom.initReceive",defaultMessage:"set pin [PIN] to ir receiver"}),inputs:{PIN:s.boardPins?{menu:s.boardPins.in}:{type:"positive_integer",defaultValue:"1"}},ino(r){let e=s.boardPins?r.getFieldValue("PIN"):this.valueToCode(r,"PIN",this.ORDER_NONE);return this.definitions_.include_irremote="#include <IRremote.h>",this.definitions_.setup_irreceiver=`IrReceiver.begin(${e});`,""}},{id:"whenReceived",text:d(n,{id:"blocks.infraredcom.whenReceived",defaultMessage:"when ir received"}),hat:!0,ino(r){this.definitions_.include_irremote="#include <IRremote.h>";let e="irreceiver_whenreceived";this.definitions_.tick_irreceiver=`${e}();`,this.definitions_.declare_irreceiver=`void ${e}();`;let c=this.statementToCode(r)||"",i="";return i+=`void ${e}() {
`,i+=`  bool received = IrReceiver.decode();
`,i+=`  IrReceiver.resume();
`,i+=`  if (!received || IrReceiver.decodedIRData.protocol == UNKNOWN) return;
`,i+=`${c}}
`,this.definitions_[e]=i,""}},{id:"receive",text:d(n,{id:"blocks.infraredcom.receive",defaultMessage:"received command"}),output:"string",ino(r){return this.definitions_.include_irremote="#include <IRremote.h>",["IrReceiver.decodedIRData.command",this.ORDER_ATOMIC]}},{id:"receiveAddr",text:d(n,{id:"blocks.infraredcom.receiveAddr",defaultMessage:"received address"}),output:"string",ino(r){return this.definitions_.include_irremote="#include <IRremote.h>",["IrReceiver.decodedIRData.address",this.ORDER_ATOMIC]}},"---",{id:"initSend",text:d(n,{id:"blocks.infraredcom.initSend",defaultMessage:"set pin [PIN] to ir sender"}),inputs:{PIN:s.boardPins?{menu:s.boardPins.out}:{type:"positive_integer",defaultValue:"1"}},ino(r){let e=s.boardPins?r.getFieldValue("PIN"):this.valueToCode(r,"PIN",this.ORDER_NONE);return this.definitions_.include_irremote="#include <IRremote.h>",this.definitions_.setup_irsender=`IrSender.begin(${e});`,""}},{id:"send",text:d(n,{id:"blocks.infraredcom.send",defaultMessage:"send command [CMD] encode [PROTO]"}),inputs:{CMD:{type:"hex16",defaultValue:"0"},PROTO:{menu:"PROTO"}},ino(r){let e=this.valueToCode(r,"CMD",this.ORDER_NONE),c=r.getFieldValue("PROTO");this.definitions_.include_irremote="#include <IRremote.h>";let i="";return i+=`IrSender.write(${c}, 0x0, ${e}, 0);
`,i+=`IrSender.space(20);
`,i}},{id:"sendAddr",text:d(n,{id:"blocks.infraredcom.sendAddr",defaultMessage:"send command:[CMD] address:[ADDR] encode [PROTO]"}),inputs:{CMD:{type:"hex16",defaultValue:"0"},ADDR:{type:"hex16",defaultValue:"0"},PROTO:{menu:"PROTO"}},ino(r){let e=this.valueToCode(r,"CMD",this.ORDER_NONE),c=this.valueToCode(r,"ADDR",this.ORDER_NONE),i=r.getFieldValue("PROTO");this.definitions_.include_irremote="#include <IRremote.h>";let o="";return o+=`IrSender.write(${i}, ${c}, ${e}, 0);
`,o+=`IrSender.space(20);
`,o}}],m={PROTO:{items:[["NEC","NEC"],["Samsung","SAMSUNG"],["Samsung48","SAMSUNG48"],["SamsungLG","SAMSUNGLG"],["Song","SONY"],["Panasonic","PANASONIC"],["Denon","DENON"],["Sharp","SHARP"],["LG","LG"],["JVC","JVC"],["RC5","RC5"],["RC6","RC6"],["Kaseikyo JVC","KASEIKYO_JVC"],["Kaseikyo Denon","KASEIKYO_DENON"],["Kaseikyo Sharp","KASEIKYO_SHARP"],["Kaseikyo Mitsubishi","KASEIKYO_MITSUBISHI"],["NEC2","NEC2"],["Onkyo","ONKYO"],["Apple","APPLE"],["BoseWave","BOSEWAVE"],["FAST","FAST"],["Lego","LEGO_PF"]]}};var a={en:{"blocks.infraredcom.name":"Infrared Communication","blocks.infraredcom.initReceive":"set pin [PIN] to ir receiver","blocks.infraredcom.whenReceived":"when ir received","blocks.infraredcom.receive":"command","blocks.infraredcom.receiveAddr":"address","blocks.infraredcom.receiveText":"text String","blocks.infraredcom.initSend":"set pin [PIN] to ir sender","blocks.infraredcom.send":"send command [CMD] encode [PROTO]","blocks.infraredcom.sendAddr":"send command:[CMD] address:[ADDR] encode [PROTO]","blocks.infraredcom.sendText":"send text String [TEXT]"},"zh-Hans":{"blocks.infraredcom.name":"红外线通讯","blocks.infraredcom.initReceive":"初始红外接收引脚[PIN]","blocks.infraredcom.whenReceived":"当收到信号时","blocks.infraredcom.receive":"信号","blocks.infraredcom.receiveAddr":"信号地址","blocks.infraredcom.receiveText":"文本 String","blocks.infraredcom.initSend":"初始红外发送引脚[PIN]","blocks.infraredcom.send":"发送[PROTO]协议信号[CMD]","blocks.infraredcom.sendAddr":"发送[PROTO]协议信号:[CMD]地址:[ADDR]","blocks.infraredcom.sendText":"发送文本 String [TEXT]"},"zh-Hant":{"blocks.infraredcom.name":"紅外線通訊","blocks.infraredcom.initReceive":"初始紅外接收引腳[PIN]","blocks.infraredcom.whenReceived":"當收到信號時","blocks.infraredcom.receive":"信號","blocks.infraredcom.receiveAddr":"信號地址","blocks.infraredcom.receiveText":"文本 String","blocks.infraredcom.initSend":"初始紅外發送引腳[PIN]","blocks.infraredcom.send":"發送[PROTO]協議信號[CMD]","blocks.infraredcom.sendAddr":"發送[PROTO]協議信號:[CMD]地址:[ADDR]","blocks.infraredcom.sendText":"發送文本 String [TEXT]"}};var S="./assets/icon-49ctbwwk.png";import{jsx as k}from"preact/jsx-runtime";T(a);var b={icon:S,name:k(g,{id:"blocks.infraredcom.name",defaultMessage:"Infrared Communication"}),blocks:f,menus:m};export{b as default};
