import{addLocalesMessages as u,Text as p}from"@blockcode/core";import{Text as r}from"@blockcode/core";import{jsx as i}from"preact/jsx-runtime";var l=(n)=>n.editor==="@blockcode/gui-iotbit",o=(n)=>[{id:"init",text:i(r,{id:"blocks.tm1637.init",defaultMessage:"set pins CLK[CLK] DIO[DIO]"}),inputs:{CLK:l(n)?{menu:"iotOutPins",defaultValue:"22"}:{type:"positive_integer",defaultValue:2},DIO:l(n)?{menu:"iotOutPins",defaultValue:"23"}:{type:"positive_integer",defaultValue:3}},ino(e){let s=this.valueToCode(e,"CLK",this.ORDER_NONE),t=this.valueToCode(e,"DIO",this.ORDER_NONE);return this.definitions_.include_tm1637="#include <GyverTM1637.h>",this.definitions_.variable_digit1637=`GyverTM1637 _digit1637(${s}, ${t});`,this.definitions_.setup_digit1637_1="_digit1637.clear();",this.definitions_.setup_digit1637_2="_digit1637.brightness(4);",""},mpy(e){let s=l(n)?e.getFieldValue("CLK"):this.valueToCode(e,"CLK",this.ORDER_NONE),t=l(n)?e.getFieldValue("DIO"):this.valueToCode(e,"DIO",this.ORDER_NONE);return this.definitions_.digit1637=`_digit1637 = tm1637.TM1637(${s}, ${t})`,""}},"---",{id:"display",text:i(r,{id:"blocks.tm1637.display",defaultMessage:"display number [NUM]"}),inputs:{NUM:{type:"integer",defaultValue:100}},ino(e){let s=this.valueToCode(e,"NUM",this.ORDER_NONE),t="";return t+=`_digit1637.point(false, false);
`,t+=`_digit1637.displayInt(${s});
`,t},mpy(e){return`_digit1637.number(${this.valueToCode(e,"NUM",this.ORDER_NONE)})
`}},{id:"time",text:i(r,{id:"blocks.tm1637.time",defaultMessage:"set time [HH]:[MM]"}),inputs:{HH:{type:"integer",defaultValue:"0"},MM:{type:"integer",defaultValue:"0"}},ino(e){let s=this.valueToCode(e,"HH",this.ORDER_NONE),t=this.valueToCode(e,"MM",this.ORDER_NONE),a="";return a+=`_digit1637.point(true, false);
`,a+=`_digit1637.displayClock(${s} % 100, ${t} % 100);
`,a+=`if (${s} < 10) _digit1637.display(0, 0);
`,a},mpy(e){let s=this.valueToCode(e,"HH",this.ORDER_NONE),t=this.valueToCode(e,"MM",this.ORDER_NONE);return`_digit1637.numbers(${s}, ${t})
`}},{id:"clear",text:i(r,{id:"blocks.tm1637.clear",defaultMessage:"clear display"}),ino(e){return`_digit1637.clear();
`},mpy(e){return`_digit1637.clear()
`}},"---",{id:"colon",text:i(r,{id:"blocks.tm1637.colon",defaultMessage:"set colon [STATE]"}),inputs:{STATE:{type:"integer",inputMode:!0,defaultValue:"1",menu:[[i(r,{id:"blocks.tm1637.state.on",defaultMessage:"on"}),"1"],[i(r,{id:"blocks.tm1637.state.off",defaultMessage:"off"}),"0"]]}},ino(e){return`_digit1637.point(${this.valueToCode(e,"STATE",this.ORDER_NONE)==1});
`},mpy(e){return`_digit1637.colon(${this.valueToCode(e,"STATE",this.ORDER_NONE)})
`}},{id:"brightness",text:i(r,{id:"blocks.tm1637.brightness",defaultMessage:"set brightness [LEVEL]"}),inputs:{LEVEL:{shadow:"brightnessLevel",defaultValue:"7"}},ino(e){return`_digit1637.brightness(${this.valueToCode(e,"LEVEL",this.ORDER_NONE)});
`},mpy(e){return`_digit1637.brightness(${this.valueToCode(e,"LEVEL",this.ORDER_NONE)})
`}},{id:"brightnessLevel",shadow:!0,output:"number",inputs:{LEVEL:{type:"slider",defaultValue:0,min:0,max:7}},mpy(e){return[e.getFieldValue("LEVEL")||0,this.ORDER_NONE]},ino(e){return[e.getFieldValue("LEVEL")||0,this.ORDER_NONE]}}],f={iotOutPins:{items:[["P0","33"],["P1","32"],["P5","0"],["P6","16"],["P7","17"],["P8","26"],["P9","25"],["P11","2"],["P13","18"],["P14","19"],["P15","21"],["P16","5"],["P19","22"],["P20","23"],["P23","27"],["P24","14"],["P25","12"],["P26","13"],["P27","15"],["P28","4"]]}};var m="./assets/tm1637-mz8y7b6s.py";var d=(n)=>{if(n.editor!=="@blockcode/gui-arduino")return[{name:"tm1637",type:"text/x-python",uri:m}];return[]};var g={en:{"blocks.tm1637.name":"TM1637 Clock","blocks.tm1637.init":"set pins CLK[CLK] DIO[DIO]","blocks.tm1637.display":"display number [NUM]","blocks.tm1637.time":"display time [HH]:[MM]","blocks.tm1637.digit":"set digit [DIGIT] at [POS]","blocks.tm1637.brightness":"set brightness [LEVEL]","blocks.tm1637.colon":"set colon [STATE]","blocks.tm1637.state.on":"on","blocks.tm1637.state.off":"off","blocks.tm1637.clear":"clear display"},"zh-Hans":{"blocks.tm1637.name":"TM1637 时钟数码管","blocks.tm1637.init":"初始引脚 CLK[CLK] DIO[DIO]","blocks.tm1637.display":"显示数字[NUM]","blocks.tm1637.time":"显示时间[HH]:[MM]","blocks.tm1637.digit":"将第[POS]位数字设为[DIGIT]","blocks.tm1637.brightness":"将亮度设为[LEVEL]","blocks.tm1637.colon":"[STATE]冒号","blocks.tm1637.state.on":"开启","blocks.tm1637.state.off":"关闭","blocks.tm1637.clear":"清除显示"},"zh-Hant":{"blocks.tm1637.name":"TM1637 時鐘數碼管","blocks.tm1637.init":"初始引腳 CLK[CLK] DIO[DIO]","blocks.tm1637.display":"顯示數字[NUM]","blocks.tm1637.time":"顯示時間[HH]:[MM]","blocks.tm1637.digit":"將第[POS]位數字設為[DIGIT]","blocks.tm1637.brightness":"將亮度設為[LEVEL]","blocks.tm1637.colon":"[STATE]冒號","blocks.tm1637.state.on":"開啟","blocks.tm1637.state.off":"關閉","blocks.tm1637.clear":"清除顯示"}};var _="./assets/icon-xhj02e3h.png";import{jsx as M}from"preact/jsx-runtime";u(g);var Y={icon:_,name:M(p,{id:"blocks.tm1637.name",defaultMessage:"TM1637 Clock"}),files:d,blocks:o,menus:f};export{Y as default};
