import{addLocalesMessages as g,Text as y}from"@blockcode/core";import{Text as r}from"@blockcode/core";import{jsx as _}from"preact/jsx-runtime";var k=(e)=>e.editor!=="@blockcode/gui-arduino",a=(e)=>e.editor==="@blockcode/gui-iotbit",n=(e)=>{e.definitions_.include_ht16k33="#include <HT16K33.h>",e.definitions_.variable_digit16k33="HT16K33 _digit16k33(0x70);",e.definitions_.setup_wire="Wire.begin();",e.definitions_.setup_digit16k33="_digit16k33.begin();"},l=(e)=>[k(e)&&{id:"init",text:_(r,{id:"blocks.vk16k33.init",defaultMessage:"set pins SCL[SCL] SDA[SDA]"}),inputs:{SCL:e.boardPins?{menu:e.boardPins.out,defaultValue:a(e)?"22":"2"}:{type:"positive_integer",defaultValue:2},SDA:e.boardPins?{menu:e.boardPins.out,defaultValue:a(e)?"23":"3"}:{type:"positive_integer",defaultValue:3}},mpy(i){let t=e.boardPins?i.getFieldValue("SCL"):this.valueToCode(i,"SCL",this.ORDER_NONE),s=e.boardPins?i.getFieldValue("SDA"):this.valueToCode(i,"SDA",this.ORDER_NONE);return this.definitions_.digit16k33=`_digit16k33 = decimal16k33.Decimal(${t}, ${s})`,""}},"---",{id:"display",text:_(r,{id:"blocks.vk16k33.display",defaultMessage:"display number [NUM]"}),inputs:{NUM:{type:"number",defaultValue:100}},ino(i){n(this);let t=this.valueToCode(i,"NUM",this.ORDER_NONE),s="";return s+=`void ht16k33DisplayNumber(float number) {
`,s+=`  _digit16k33.setDigits(1);
`,s+=`  _digit16k33.displayColon(0);
`,s+=`  char buffer[15];
`,s+=`  dtostrf(number, 0, 3, buffer);
`,s+=`  char *dot = strchr(buffer, '.');
`,s+=`  if (dot == NULL) {
`,s+=`    _digit16k33.displayInt((int)number);
`,s+=`    return;
`,s+=`  }
`,s+=`  char *frac = dot + 1;
`,s+=`  int len = strlen(frac);
`,s+=`  while (len > 0 && frac[len - 1] == '0') {
`,s+=`    len--;
`,s+=`  }
`,s+=`  len > 0 ? _digit16k33.displayFloat(number, len) : _digit16k33.displayInt((int)number);
`,s+=`}
`,this.definitions_.declare_ht16k33DisplayNumber="void ht16k33DisplayNumber(float number);",this.definitions_.ht16k33DisplayNumber=s,`ht16k33DisplayNumber(${t});
`},mpy(i){return`_digit16k33.show_number(${this.valueToCode(i,"NUM",this.ORDER_NONE)})
`}},{id:"time",text:_(r,{id:"blocks.vk16k33.time",defaultMessage:"set time [HH]:[MM]"}),inputs:{HH:{type:"integer",defaultValue:"0"},MM:{type:"integer",defaultValue:"0"}},ino(i){n(this);let t=this.valueToCode(i,"HH",this.ORDER_NONE),s=this.valueToCode(i,"MM",this.ORDER_NONE),o="";return o+=`_digit16k33.suppressLeadingZeroPlaces(0);
`,o+=`_digit16k33.displayTime(${t}, ${s});
`,o},mpy(i){let t=this.valueToCode(i,"HH",this.ORDER_NONE),s=this.valueToCode(i,"MM",this.ORDER_NONE);return`_digit16k33.show_time(${t}, ${s})
`}},{id:"clear",text:_(r,{id:"blocks.vk16k33.clear",defaultMessage:"clear display"}),ino(i){return n(this),`_digit16k33.displayClear();
`},mpy(i){return`_digit16k33.clear()
`}},"---",{id:"colon",text:_(r,{id:"blocks.vk16k33.colon",defaultMessage:"set colon [STATE]"}),inputs:{STATE:{type:"integer",inputMode:!0,defaultValue:"1",menu:[[_(r,{id:"blocks.vk16k33.state.on",defaultMessage:"on"}),"1"],[_(r,{id:"blocks.vk16k33.state.off",defaultMessage:"off"}),"0"]]}},ino(i){return n(this),`_digit16k33.displayColon(${this.valueToCode(i,"STATE",this.ORDER_NONE)});
`},mpy(i){return`_digit16k33.show_colon(${this.valueToCode(i,"STATE",this.ORDER_NONE)})
`}},{id:"brightness",text:_(r,{id:"blocks.vk16k33.brightness",defaultMessage:"set brightness [LEVEL]"}),inputs:{LEVEL:{shadow:"brightnessLevel",defaultValue:"9"}},ino(i){return n(this),`_digit16k33.setBrightness(${this.valueToCode(i,"LEVEL",this.ORDER_NONE)});
`},mpy(i){return`_digit16k33.brightness(${this.valueToCode(i,"LEVEL",this.ORDER_NONE)})
`}},{id:"brightnessLevel",shadow:!0,output:"number",inputs:{LEVEL:{type:"slider",defaultValue:0,min:0,max:15}},mpy(i){return[i.getFieldValue("LEVEL")||0,this.ORDER_NONE]},ino(i){return[i.getFieldValue("LEVEL")||0,this.ORDER_NONE]}},{id:"frequency",text:_(r,{id:"blocks.vk16k33.frequency",defaultMessage:"set blink frequency [FREQ]"}),inputs:{FREQ:{type:"integer",defaultValue:"0",menu:[["2Hz","1"],["1Hz","2"],["0.5Hz","3"],[_(r,{id:"blocks.vk16k33.state.off",defaultMessage:"off"}),"0"]]}},ino(i){return n(this),`_digit16k33.setBlink(${i.getFieldValue("FREQ")||0});
`},mpy(i){return`_digit16k33.blink_rate(${i.getFieldValue("FREQ")||0})
`}}].filter(Boolean);var f="./assets/x16k33-rwhenb05.py";var d="./assets/decimal16k33-y6r632c3.py";var c=(e)=>{if(e.editor!=="@blockcode/gui-arduino")return[{name:"decimal16k33",type:"text/x-python",uri:d},{common:!0,name:"x16k33",type:"text/x-python",uri:f}];return[]};var b={en:{"blocks.vk16k33.name":"VK16K33 4-Digit","blocks.vk16k33.init":"set pins SCL[SCL] SDA[SDA]","blocks.vk16k33.addr":"set I2C address [ADDR]","blocks.vk16k33.display":"display number [NUM]","blocks.vk16k33.time":"display time [HH]:[MM]","blocks.vk16k33.digit":"set digit [DIGIT] at [POS]","blocks.vk16k33.brightness":"set brightness [LEVEL]","blocks.vk16k33.colon":"set colon [STATE]","blocks.vk16k33.state.on":"on","blocks.vk16k33.state.off":"off","blocks.vk16k33.frequency":"set blink frequency [FREQ]","blocks.vk16k33.clear":"clear display"},"zh-Hans":{"blocks.vk16k33.name":"VK16K33 四位数码管","blocks.vk16k33.init":"初始引脚 SCL[SCL] SDA[SDA]","blocks.vk16k33.addr":"初始 I2C 地址[ADDR]","blocks.vk16k33.display":"显示数字[NUM]","blocks.vk16k33.time":"显示时间[HH]:[MM]","blocks.vk16k33.digit":"将第[POS]位数字设为[DIGIT]","blocks.vk16k33.brightness":"将亮度设为[LEVEL]","blocks.vk16k33.colon":"[STATE]冒号","blocks.vk16k33.state.on":"开启","blocks.vk16k33.state.off":"关闭","blocks.vk16k33.frequency":"将闪烁频率设为[FREQ]","blocks.vk16k33.clear":"清除显示"},"zh-Hant":{"blocks.vk16k33.name":"VK16K33 四位數碼管","blocks.vk16k33.init":"初始引腳 SCL[SCL] SDA[SDA]","blocks.vk16k33.addr":"初始 I2C 地址[ADDR]","blocks.vk16k33.display":"顯示數字[NUM]","blocks.vk16k33.time":"顯示時間[HH]:[MM]","blocks.vk16k33.digit":"將第[POS]位數字設為[DIGIT]","blocks.vk16k33.brightness":"將亮度設為[LEVEL]","blocks.vk16k33.colon":"[STATE]冒號","blocks.vk16k33.state.on":"開啟","blocks.vk16k33.state.off":"關閉","blocks.vk16k33.frequency":"將閃爍頻率設為[FREQ]","blocks.vk16k33.clear":"清除顯示"}};var p="./assets/icon-8x86xw9p.png";import{jsx as S}from"preact/jsx-runtime";g(b);var B={icon:p,name:S(y,{id:"blocks.vk16k33.name",defaultMessage:"VK16K33 4-Digit"}),files:c,blocks:l};export{B as default};
