import{addLocalesMessages as x,Text as y}from"@blockcode/core";import{Text as a}from"@blockcode/core";import{jsx as r}from"preact/jsx-runtime";var u=(s)=>s.editor!=="@blockcode/gui-arduino",o=(s)=>s.editor==="@blockcode/gui-iotbit",d=(s)=>[u(s)&&{id:"init",text:r(a,{id:"blocks.bmx280.init",defaultMessage:"set pins SCL[SCL] SDA[SDA]"}),inputs:{SCL:o(s)?{menu:"iotOutPins",defaultValue:"22"}:{type:"integer",defaultValue:"2"},SDA:o(s)?{menu:"iotOutPins",defaultValue:"23"}:{type:"integer",defaultValue:"3"}},mpy(t){let e=o(s)?t.getFieldValue("SCL"):this.valueToCode(t,"SCL",this.ORDER_NONE),n=o(s)?t.getFieldValue("SDA"):this.valueToCode(t,"SDA",this.ORDER_NONE);if(this.definitions_.bmx280_addr){let f=this.definitions_.bmx280_addr.replace("# BMx280 addr: ","");this.definitions_.bmx280=`_bmx280 = bmx280.BMx280(${e}, ${n}, ${f})`,delete this.definitions_.bmx280_addr}else this.definitions_.bmx280=`_bmx280 = bmx280.BMx280(${e}, ${n})`;let i="";return i+=`def get_bmx280_value(mode=2):
`,i+=`  _bmx280.read()
`,i+=`  if mode == 1: return _bmx280.temperature
`,i+=`  if mode == 2: return _bmx280.pressure
`,i+=`  if mode == 3: return _bmx280.humidity
`,i+=`  if mode == 4: return _bmx280.altitude
`,this.definitions_.get_bmx280_value=i,""}},{id:"addr",text:r(a,{id:"blocks.bmx280.addr",defaultMessage:"set I2C address [ADDR]"}),inputs:{ADDR:{menu:[["0×76","0x76"],["0×77","0x77"]]}},ino(t){let e=t.getFieldValue("ADDR");return this.definitions_.include_bmx280="#include <BMx280.h>",this.definitions_.variable_bmx280="BMx280 _bmx280;",this.definitions_.setup_bmx280=`_bmx280.beginI2C(${e});`,""},mpy(t){let e=t.getFieldValue("ADDR");if(this.definitions_.bmx280)this.definitions_.bmx280=this.definitions_.bmx280.replace(/(\d+)\)$/,`$1, ${e})`);else this.definitions_.bmx280_addr=`# BMx280 addr: ${e}`;return""}},"---",{id:"pressure",text:r(a,{id:"blocks.bmx280.pressure",defaultMessage:"pressure atmosphere"}),output:"number",ino(t){if(this.definitions_.include_bmx280="#include <BMx280.h>",this.definitions_.variable_bmx280="BMx280 _bmx280;",!this.definitions_.setup_bmx280)this.definitions_.setup_bmx280="_bmx280.beginI2C();";let e="";return e+=`float getBMx280Value(int mode) {
`,e+=`  float T, P_hPa, H;
`,e+=`  _bmx280.read280(T, P_hPa, H);
`,e+=`  return mode == 1 ? T : (mode == 2 ? P_hPa : (mode == 3 && _bmx280.hasHumidity() ? H : 0.0));
`,e+="}",this.definitions_.declare_getBMx280Value="float getBMx280Value(int mode = 2);",this.definitions_.getBMx280Value=e,["getBMx280Value()",this.ORDER_FUNCTION_CALL]},mpy(t){return["get_bmx280_value()",this.ORDER_FUNCTION_CALL]}},{id:"altitude",text:r(a,{id:"blocks.bmx280.altitude",defaultMessage:"altitude"}),output:"number",ino(t){if(this.definitions_.include_bmx280="#include <BMx280.h>",this.definitions_.variable_bmx280="BMx280 _bmx280;",!this.definitions_.setup_bmx280)this.definitions_.setup_bmx280="_bmx280.beginI2C();";return["_bmx280.readAltitude()",this.ORDER_FUNCTION_CALL]},mpy(t){return this.definitions_.get_bmx280_value=bmxCode,["get_bmx280_value(4)",this.ORDER_FUNCTION_CALL]}},{id:"temperature",text:r(a,{id:"blocks.bmx280.temperature",defaultMessage:"temperature"}),output:"number",ino(t){if(this.definitions_.include_bmx280="#include <BMx280.h>",this.definitions_.variable_bmx280="BMx280 _bmx280;",!this.definitions_.setup_bmx280)this.definitions_.setup_bmx280="_bmx280.beginI2C();";let e="";return e+=`float getBMx280Value(int mode) {
`,e+=`  float T, P_hPa, H;
`,e+=`  _bmx280.read280(T, P_hPa, H);
`,e+=`  return mode == 1 ? T : (mode == 2 ? P_hPa : (mode == 3 && _bmx280.hasHumidity() ? H : 0.0));
`,e+="}",this.definitions_.declare_getBMx280Value="float getBMx280Value(int mode = 2);",this.definitions_.getBMx280Value=e,["getBMx280Value(1)",this.ORDER_FUNCTION_CALL]},mpy(t){return["get_bmx280_value(1)",this.ORDER_FUNCTION_CALL]}},{id:"humidity",text:r(a,{id:"blocks.bmx280.humidity",defaultMessage:"humidity"}),output:"number",ino(t){if(this.definitions_.include_bmx280="#include <BMx280.h>",this.definitions_.variable_bmx280="BMx280 _bmx280;",!this.definitions_.setup_bmx280)this.definitions_.setup_bmx280="_bmx280.beginI2C();";let e="";return e+=`float getBMx280Value(int mode) {
`,e+=`  float T, P_hPa, H;
`,e+=`  _bmx280.read280(T, P_hPa, H);
`,e+=`  return mode == 1 ? T : (mode == 2 ? P_hPa : (mode == 3 && _bmx280.hasHumidity() ? H : 0.0));
`,e+="}",this.definitions_.declare_getBMx280Value="float getBMx280Value(int mode = 2);",this.definitions_.getBMx280Value=e,["getBMx280Value(3)",this.ORDER_FUNCTION_CALL]},mpy(t){return["get_bmx280_value(3)",this.ORDER_FUNCTION_CALL]}}].filter(Boolean),_={iotOutPins:{items:[["P0","33"],["P1","32"],["P5","0"],["P6","16"],["P7","17"],["P8","26"],["P9","25"],["P11","2"],["P13","18"],["P14","19"],["P15","21"],["P16","5"],["P19","22"],["P20","23"],["P23","27"],["P24","14"],["P25","12"],["P26","13"],["P27","15"],["P28","4"]]}};var l="./assets/bmx280-x2q5zv14.py";var m={en:{"blocks.bmx280.name":"BMx280","blocks.bmx280.init":"set pins SCL[SCL] SDA[SDA]","blocks.bmx280.addr":"set I2C address [ADDR]","blocks.bmx280.pressure":"pressure atmosphere","blocks.bmx280.temperature":"temperature","blocks.bmx280.humidity":"humidity","blocks.bmx280.altitude":"altitude"},"zh-Hans":{"blocks.bmx280.name":"BMx280 气压","blocks.bmx280.init":"初始引脚 SCL[SCL] SDA[SDA]","blocks.bmx280.addr":"初始 I2C 地址[ADDR]","blocks.bmx280.pressure":"气压","blocks.bmx280.temperature":"温度","blocks.bmx280.humidity":"湿度","blocks.bmx280.altitude":"海拔"},"zh-Hant":{"blocks.bmx280.name":"BMx280 氣壓","blocks.bmx280.init":"初始引腳 SCL[SCL] SDA[SDA]","blocks.bmx280.addr":"初始 I2C 地址[ADDR]","blocks.bmx280.pressure":"氣壓","blocks.bmx280.temperature":"溫度","blocks.bmx280.humidity":"濕度","blocks.bmx280.altitude":"海拔"}};var c="./assets/icon-pz4ha9b9.png";import{jsx as h}from"preact/jsx-runtime";x(m);var S={icon:c,name:h(y,{id:"blocks.bmx280.name",defaultMessage:"BMP280"}),files(s){if(s.editor!=="@blockcode/gui-arduino")return[{name:"bmx280",type:"text/x-python",uri:l}];return[]},blocks:d,menus:_};export{S as default};
