import{addLocalesMessages as h,Text as B}from"@blockcode/core";import{Text as a}from"@blockcode/core";import{jsx as r}from"preact/jsx-runtime";var _=(t)=>!["@blockcode/gui-arduino","@nulllab/gui-lgtuino"].includes(t.editor),c=(t)=>t.editor==="@emakefun/gui-iotbit",m=(t)=>[{id:"addr",hidden:_(t),text:r(a,{id:"blocks.bmx280.addr",defaultMessage:"set I2C address [ADDR]"}),inputs:{ADDR:{menu:[["0×76","0x76"],["0×77","0x77"]]}},ino(s){let e=s.getFieldValue("ADDR");return this.definitions_.include_bmx280="#include <BMx280.h>",this.definitions_.variable_bmx280="BMx280 _bmx280;",this.definitions_.setup_bmx280=`_bmx280.beginI2C(${e});`,""}},_(t)&&{id:"init",text:r(a,{id:"blocks.bmx280.init",defaultMessage:"set BMx280 pins SCL:[SCL] SDA:[SDA] I2C address [ADDR]"}),inputs:{SCL:t.boardPins?{menu:t.boardPins.out,defaultValue:c(t)?"P19":"2"}:{type:"integer",defaultValue:"2"},SDA:t.boardPins?{menu:t.boardPins.all,defaultValue:c(t)?"P20":"3"}:{type:"integer",defaultValue:"3"},ADDR:{menu:[["0×76","0x76"],["0×77","0x77"]]}},mpy(s,e,o){let n=t.boardPins,l=n?.i2c&&n.i2c.scl===e.SCL&&n.i2c.sda===e.SDA?n.i2c.channel:1,d=`i2c${l}_${e.SCL}_${e.SDA}`;o.import_pin="from machine import Pin",o.import_i2c="from machine import I2C",o[d]=`${d} = I2C(${l}, scl=Pin(${e.SCL}), sda=Pin(${e.SDA}))`,o.bmx280=`_bmx280 = bmx280.BMx280(${d}, ${e.ADDR})`;let i="";return i+=`def get_bmx280_value(mode=2):
`,i+=`  _bmx280.read()
`,i+=`  if mode == 1: return _bmx280.temperature
`,i+=`  if mode == 2: return _bmx280.pressure
`,i+=`  if mode == 3: return _bmx280.humidity
`,i+=`  if mode == 4: return _bmx280.altitude
`,o.get_bmx280_value=i,""}},"---",{id:"pressure",text:r(a,{id:"blocks.bmx280.pressure",defaultMessage:"pressure(hPa)"}),output:"number",ino(s){if(this.definitions_.include_bmx280="#include <BMx280.h>",this.definitions_.variable_bmx280="BMx280 _bmx280;",!this.definitions_.setup_bmx280)this.definitions_.setup_bmx280="_bmx280.beginI2C();";let e="";return e+=`float getBMx280Value(int mode) {
`,e+=`  float T, P_hPa, H;
`,e+=`  _bmx280.read280(T, P_hPa, H);
`,e+=`  return mode == 1 ? T : (mode == 2 ? P_hPa : (mode == 3 && _bmx280.hasHumidity() ? H : 0.0));
`,e+="}",this.definitions_.declare_getBMx280Value="float getBMx280Value(int mode = 2);",this.definitions_.getBMx280Value=e,["getBMx280Value()",this.ORDER_FUNCTION_CALL]},mpy(s){return["get_bmx280_value()",this.ORDER_FUNCTION_CALL]}},{id:"altitude",text:r(a,{id:"blocks.bmx280.altitude",defaultMessage:"altitude"}),output:"number",ino(s){if(this.definitions_.include_bmx280="#include <BMx280.h>",this.definitions_.variable_bmx280="BMx280 _bmx280;",!this.definitions_.setup_bmx280)this.definitions_.setup_bmx280="_bmx280.beginI2C();";return["_bmx280.readAltitude()",this.ORDER_FUNCTION_CALL]},mpy(s){return this.definitions_.get_bmx280_value=bmxCode,["get_bmx280_value(4)",this.ORDER_FUNCTION_CALL]}},{id:"temperature",text:r(a,{id:"blocks.bmx280.temperature",defaultMessage:"temperature"}),output:"number",ino(s){if(this.definitions_.include_bmx280="#include <BMx280.h>",this.definitions_.variable_bmx280="BMx280 _bmx280;",!this.definitions_.setup_bmx280)this.definitions_.setup_bmx280="_bmx280.beginI2C();";let e="";return e+=`float getBMx280Value(int mode) {
`,e+=`  float T, P_hPa, H;
`,e+=`  _bmx280.read280(T, P_hPa, H);
`,e+=`  return mode == 1 ? T : (mode == 2 ? P_hPa : (mode == 3 && _bmx280.hasHumidity() ? H : 0.0));
`,e+="}",this.definitions_.declare_getBMx280Value="float getBMx280Value(int mode = 2);",this.definitions_.getBMx280Value=e,["getBMx280Value(1)",this.ORDER_FUNCTION_CALL]},mpy(s){return["get_bmx280_value(1)",this.ORDER_FUNCTION_CALL]}},{id:"humidity",text:r(a,{id:"blocks.bmx280.humidity",defaultMessage:"humidity"}),output:"number",ino(s){if(this.definitions_.include_bmx280="#include <BMx280.h>",this.definitions_.variable_bmx280="BMx280 _bmx280;",!this.definitions_.setup_bmx280)this.definitions_.setup_bmx280="_bmx280.beginI2C();";let e="";return e+=`float getBMx280Value(int mode) {
`,e+=`  float T, P_hPa, H;
`,e+=`  _bmx280.read280(T, P_hPa, H);
`,e+=`  return mode == 1 ? T : (mode == 2 ? P_hPa : (mode == 3 && _bmx280.hasHumidity() ? H : 0.0));
`,e+="}",this.definitions_.declare_getBMx280Value="float getBMx280Value(int mode = 2);",this.definitions_.getBMx280Value=e,["getBMx280Value(3)",this.ORDER_FUNCTION_CALL]},mpy(s){return["get_bmx280_value(3)",this.ORDER_FUNCTION_CALL]}}];var u="./assets/bmx280-h7hv7pjp.py";var f={en:{"blocks.bmx280.name":"BMx280","blocks.bmx280.init":"set BMx280 pins SCL:[SCL] SDA:[SDA] I2C address [ADDR]","blocks.bmx280.addr":"set BMx280 I2C address [ADDR]","blocks.bmx280.pressure":"pressure(hPa)","blocks.bmx280.temperature":"temperature(°C)","blocks.bmx280.humidity":"humidity(%)","blocks.bmx280.altitude":"altitude"},"zh-Hans":{"blocks.bmx280.name":"BMx280 气压","blocks.bmx280.init":"初始化 BMx280 引脚 SCL:[SCL] SDA:[SDA] I2C 地址[ADDR]","blocks.bmx280.addr":"初始化 BMx280 I2C 地址[ADDR]","blocks.bmx280.pressure":"气压（hPa）","blocks.bmx280.temperature":"温度（°C）","blocks.bmx280.humidity":"湿度（%）","blocks.bmx280.altitude":"海拔"},"zh-Hant":{"blocks.bmx280.name":"BMx280 氣壓","blocks.bmx280.init":"初始化 BMx280 引腳 SCL:[SCL] SDA:[SDA] I2C 地址[ADDR]","blocks.bmx280.addr":"初始化 BMx280 I2C 地址[ADDR]","blocks.bmx280.pressure":"氣壓（hPa）","blocks.bmx280.temperature":"溫度（°C）","blocks.bmx280.humidity":"濕度（%）","blocks.bmx280.altitude":"海拔"}};var p="./assets/icon-pz4ha9b9.png";import{jsx as P}from"preact/jsx-runtime";h(f);var T=(t)=>!["@blockcode/gui-arduino","@nulllab/gui-lgtuino"].includes(t.editor),R={icon:p,name:P(B,{id:"blocks.bmx280.name",defaultMessage:"BMP280"}),files(t){if(T(t))return[{header:!0,name:"bmx280",type:"text/x-python",uri:u}];return[]},blocks:m};export{R as default};
