import{addLocalesMessages as Z,Text as D}from"@blockcode/core";import{Text as d}from"@blockcode/core";import{jsx as n}from"preact/jsx-runtime";var C=(a)=>["@blockcode/gui-arduino","@nulllab/gui-lgtuino"].includes(a.editor),L=(a)=>a.editor==="@emakefun/gui-iotbit",c=(a)=>[C(a)?{id:"init",text:n(d,{id:"blocks.lcd.init",defaultMessage:"set lcd display [SIZE] I2C address:[ADDR]"}),inputs:{SIZE:{defaultValue:"16,2",menu:[["0801","8,1"],["0802","8,2"],["1601","16,1"],["1602","16,2"],["1604","16,4"],["2002","20,2"],["2004","20,4"],["2402","24,2"],["4002","40,2"],["4004","40,4"]]},ADDR:{menu:[["0×27","0x27"],["0×26","0x26"],["0×25","0x25"],["0×24","0x24"],["0×23","0x23"],["0×22","0x22"],["0×21","0x21"],["0×20","0x20"]]}},ino(e){let t=e.getFieldValue("SIZE"),i=e.getFieldValue("ADDR");return this.definitions_.include_lcdi2c="#include <LCDI2C_Generic.h>",this.definitions_.variable_lcd=`LCDI2C_Generic lcd(${i}, ${t});`,this.definitions_.setup_lcd=`lcd.init();
lcd.setBacklight(1);`,""}}:{id:"initI2c",text:n(d,{id:"blocks.lcd.initI2c",defaultMessage:"set lcd display [SIZE] SCL:[SCL] SDA:[SDA] I2C address:[ADDR]"}),inputs:{SIZE:{defaultValue:"16,2",menu:[["0801","8,1"],["0802","8,2"],["1601","16,1"],["1602","16,2"],["1604","16,4"],["2002","20,2"],["2004","20,4"],["2402","24,2"],["4002","40,2"],["4004","40,4"]]},SCL:a.boardPins?{menu:a.boardPins.out,defaultValue:L(a)?"P19":"2"}:{type:"integer",defaultValue:"2"},SDA:a.boardPins?{menu:a.boardPins.all,defaultValue:L(a)?"P20":"3"}:{type:"integer",defaultValue:"3"},ADDR:{menu:[["0×27","0x27"],["0×26","0x26"],["0×25","0x25"],["0×24","0x24"],["0×23","0x23"],["0×22","0x22"],["0×21","0x21"],["0×20","0x20"]]}},mpy(e,t,i){let l=a.boardPins,o=l?.i2c&&l.i2c.scl===t.SCL&&l.i2c.sda===t.SDA?l.i2c.channel:1,s=`i2c${o}_${t.SCL}_${t.SDA}`;return i.import_pin="from machine import Pin",i.import_i2c="from machine import I2C",i[s]=`${s} = I2C(${o}, scl=Pin(${t.SCL}), sda=Pin(${t.SDA}))`,i.lcdi2c=`lcd = lcdi2c.LCD_I2C(${s}, ${t.SIZE}, ${t.ADDR})`,""}},{id:"backlight",text:n(d,{id:"blocks.lcd.backlight",defaultMessage:"set backlight [STATE]"}),inputs:{STATE:{inputMode:!0,type:"integer",defaultValue:"1",menu:[[n(d,{id:"blocks.lcd.stateOn",defaultMessage:"on"}),"1"],[n(d,{id:"blocks.lcd.stateOff",defaultMessage:"off"}),"0"]]}},ino(e){return`lcd.setBacklight(${this.valueToCode(e,"STATE",this.ORDER_NONE)});
`},mpy(e){return`lcd.backlight(${this.valueToCode(e,"STATE",this.ORDER_NONE)})
`}},"---",C(a)&&{id:"text",text:n(d,{id:"blocks.lcd.text",defaultMessage:"display [TEXT] delay [SEC] second"}),inputs:{TEXT:{type:"string",defaultValue:"Hello World"},SEC:{type:"positive_integer",defaultValue:"1"}},ino(e){let t=this.valueToCode(e,"TEXT",this.ORDER_NONE),i=this.valueToCode(e,"SEC",this.ORDER_NONE),l="";return l+=`lcd.home();
`,l+=`lcd.print(${t}, ${i});
`,l}},{id:"textLine",text:n(d,{id:"blocks.lcd.textLine",defaultMessage:"display [TEXT] at line [LINE]"}),inputs:{TEXT:{type:"string",defaultValue:"Hello"},LINE:{menu:[1,2,3,4]}},ino(e){let t=this.valueToCode(e,"TEXT",this.ORDER_NONE),i=e.getFieldValue("LINE"),l="";return l+=`lcd.setCursor(0, ${i-1});
`,l+=`lcd.println(${t});
`,l},mpy(e){let t=this.valueToCode(e,"TEXT",this.ORDER_NONE),i=e.getFieldValue("LINE"),l="";return l+=`lcd.set_cursor(0, ${i-1})
`,l+=`lcd.print(${t})
`,l}},{id:"textXY",text:n(d,{id:"blocks.lcd.textXY",defaultMessage:"display [TEXT] at row:[ROW] col:[COL]"}),inputs:{TEXT:{type:"string",defaultValue:"Hello"},ROW:{type:"positive_integer",defaultValue:"1"},COL:{type:"positive_integer",defaultValue:"1"}},ino(e){let t=this.valueToCode(e,"TEXT",this.ORDER_NONE),i=this.getAdjusted(e,"ROW"),l=this.getAdjusted(e,"COL"),o="";return o+=`lcd.setCursor(${l}, ${i});
`,o+=`lcd.println(${t});
`,o},mpy(e){let t=this.valueToCode(e,"TEXT",this.ORDER_NONE),i=this.getAdjusted(e,"ROW"),l=this.getAdjusted(e,"COL"),o="";return o+=`lcd.set_cursor(${l}, ${i})
`,o+=`lcd.print(${t});
`,o}},{id:"clear",text:n(d,{id:"blocks.lcd.clear",defaultMessage:"clear"}),ino(e){return`lcd.clear();
`},mpy(e){return`lcd.clear()
`}}];var f="./assets/lcdi2c-t2b966gp.py";var k=(a)=>["@blockcode/gui-arduino","@nulllab/gui-lgtuino"].includes(a.editor),r=(a)=>{if(k(a))return[];return[{header:!0,name:"lcdi2c.py",type:"text/x-python",uri:f}]};var p={en:{"blocks.lcd.name":"LCD","blocks.lcd.init":"set lcd display [SIZE] I2C address [ADDR]","blocks.lcd.initI2c":"set lcd display [SIZE] pins SCL:[SCL] SDA:[SDA] I2C address:[ADDR]","blocks.lcd.backlight":"set backlight [STATE]","blocks.lcd.stateOn":"on","blocks.lcd.stateOff":"off","blocks.lcd.text":"display [TEXT] delay [SEC] second","blocks.lcd.textLine":"display [TEXT] at line [LINE]","blocks.lcd.textXY":"display [TEXT] at row:[ROW] col:[COL]","blocks.lcd.clear":"clear"},"zh-Hans":{"blocks.lcd.name":"LCD 显示屏","blocks.lcd.init":"初始化 LCD 显示屏 [SIZE] I2C 地址 [ADDR]","blocks.lcd.initI2c":"初始化 LCD 显示屏 [SIZE] 引脚 SCL:[SCL] SDA:[SDA] I2C 地址:[ADDR]","blocks.lcd.backlight":"[STATE] 背光","blocks.lcd.stateOn":"开","blocks.lcd.stateOff":"关","blocks.lcd.text":"显示 [TEXT] 延迟 [SEC] 秒","blocks.lcd.textLine":"在第 [LINE] 行显示 [TEXT]","blocks.lcd.textXY":"在第 [ROW] 行第 [COL] 行列显示 [TEXT]","blocks.lcd.clear":"清除"},"zh-Hant":{"blocks.lcd.name":"LCD 顯示屏","blocks.lcd.init":"初始化 LCD 顯示屏 [SIZE] I2C 地址 [ADDR]","blocks.lcd.initI2c":"初始化 LCD 顯示屏 [SIZE] 引腳 SCL:[SCL] SDA:[SDA] I2C 地址:[ADDR]","blocks.lcd.backlight":"[STATE] 背光","blocks.lcd.stateOn":"開","blocks.lcd.stateOff":"關","blocks.lcd.text":"顯示 [TEXT] 延遲 [SEC] 秒","blocks.lcd.textLine":"在第 [LINE] 行顯示 [TEXT]","blocks.lcd.textXY":"在第 [ROW] 行第 [COL] 行列顯示 [TEXT]","blocks.lcd.clear":"清除"}};var h="./assets/icon-aqeksxsf.svg";import{jsx as u}from"preact/jsx-runtime";Z(p);var $={icon:h,name:u(D,{id:"blocks.lcd.name",defaultMessage:"LCD"}),files:r,blocks:c};export{$ as default};
