import{addLocalesMessages as c,Text as h}from"@blockcode/core";import{Text as e}from"@blockcode/core";import{jsx as o}from"preact/jsx-runtime";var C=(f)=>[{id:"init",text:o(e,{id:"blocks.lcd.init",defaultMessage:"set lcd display [SIZE] address [ADDR]"}),inputs:{SIZE:{defaultValue:"16,2",menu:[["0801","8,1"],["0802","8,2"],["1601","16,1"],["1602","16,2"],["1604","16,4"],["2002","20,2"],["2004","20,4"],["2402","24,2"],["4002","40,2"],["4004","40,4"]]},ADDR:{menu:[["0×27","0x27"],["0×26","0x26"],["0×25","0x25"],["0×24","0x24"],["0×23","0x23"],["0×22","0x22"],["0×21","0x21"],["0×20","0x20"]]}},ino(t){let a=t.getFieldValue("SIZE"),l=t.getFieldValue("ADDR");return this.definitions_.include_lcdi2c="#include <LCDI2C_Generic.h>",this.definitions_.variable_lcd=`LCDI2C_Generic lcd(${l}, ${a});`,this.definitions_.setup_lcd="lcd.init();",""}},{id:"backlight",text:o(e,{id:"blocks.lcd.backlight",defaultMessage:"set backlight [STATE]"}),inputs:{STATE:{inputMode:!0,type:"integer",defaultValue:"1",menu:[[o(e,{id:"blocks.lcd.stateOn",defaultMessage:"on"}),"1"],[o(e,{id:"blocks.lcd.stateOff",defaultMessage:"off"}),"0"]]}},ino(t){return`lcd.setBacklight(${this.valueToCode(t,"STATE",this.ORDER_NONE)});
`}},"---",{id:"text",text:o(e,{id:"blocks.lcd.text",defaultMessage:"display [TEXT] delay [SEC] second"}),inputs:{TEXT:{type:"string",defaultValue:"Hello World"},SEC:{type:"positive_integer",defaultValue:"1"}},ino(t){let a=this.valueToCode(t,"TEXT",this.ORDER_NONE),l=this.valueToCode(t,"SEC",this.ORDER_NONE),i="";return i+=`lcd.home();
`,i+=`lcd.print(${a}, ${l});
`,i}},{id:"textLine",text:o(e,{id:"blocks.lcd.textLine",defaultMessage:"display [TEXT] at line [LINE]"}),inputs:{TEXT:{type:"string",defaultValue:"Hello"},LINE:{menu:[1,2,3,4]}},ino(t){let a=this.valueToCode(t,"TEXT",this.ORDER_NONE),l=t.getFieldValue("LINE"),i="";return i+=`lcd.setCursor(0, ${l-1});
`,i+=`lcd.println(${a});
`,i}},{id:"textXY",text:o(e,{id:"blocks.lcd.textXY",defaultMessage:"display [TEXT] at row:[ROW] col:[COL]"}),inputs:{TEXT:{type:"string",defaultValue:"Hello"},ROW:{type:"positive_integer",defaultValue:"1"},COL:{type:"positive_integer",defaultValue:"1"}},ino(t){let a=this.valueToCode(t,"TEXT",this.ORDER_NONE),l=this.getAdjusted(t,"ROW"),i=this.getAdjusted(t,"COL"),d="";return d+=`lcd.setCursor(${i}, ${l});
`,d+=`lcd.println(${a});
`,d}},{id:"clear",text:o(e,{id:"blocks.lcd.clear",defaultMessage:"clear"}),ino(t){return`lcd.clear();
`}}];var n={en:{"blocks.lcd.name":"LCD","blocks.lcd.init":"set lcd display [SIZE] i2c address [ADDR]","blocks.lcd.backlight":"set backlight [STATE]","blocks.lcd.stateOn":"on","blocks.lcd.stateOff":"off","blocks.lcd.text":"display [TEXT] delay [SEC] second","blocks.lcd.textLine":"display [TEXT] at line [LINE]","blocks.lcd.textXY":"display [TEXT] at row:[ROW] col:[COL]","blocks.lcd.clear":"clear"},"zh-Hans":{"blocks.lcd.name":"LCD 显示屏","blocks.lcd.init":"初始 LCD 显示屏 [SIZE] I2C 地址 [ADDR]","blocks.lcd.backlight":"[STATE] 背光","blocks.lcd.stateOn":"开","blocks.lcd.stateOff":"关","blocks.lcd.text":"显示 [TEXT] 延迟 [SEC] 秒","blocks.lcd.textLine":"在第 [LINE] 行显示 [TEXT]","blocks.lcd.textXY":"在第 [ROW] 行第 [COL] 行列显示 [TEXT]","blocks.lcd.clear":"清除"},"zh-Hant":{"blocks.lcd.name":"LCD 顯示屏","blocks.lcd.init":"初始 LCD 顯示屏 [SIZE] I2C 地址 [ADDR]","blocks.lcd.backlight":"[STATE] 背光","blocks.lcd.stateOn":"開","blocks.lcd.stateOff":"關","blocks.lcd.text":"顯示 [TEXT] 延遲 [SEC] 秒","blocks.lcd.textLine":"在第 [LINE] 行顯示 [TEXT]","blocks.lcd.textXY":"在第 [ROW] 行第 [COL] 行列顯示 [TEXT]","blocks.lcd.clear":"清除"}};var L="./assets/icon-aqeksxsf.svg";import{jsx as r}from"preact/jsx-runtime";c(n);var O={icon:L,name:r(h,{id:"blocks.lcd.name",defaultMessage:"LCD"}),blocks:C};export{O as default};
