import{addLocalesMessages as h,Text as I}from"@blockcode/core";import{Text as o}from"@blockcode/core";var l="./assets/turn-left-3ncjj928.svg";var i="./assets/turn-right-ny3de90q.svg";import{jsx as n}from"preact/jsx-runtime";var p=(r)=>r.editor==="@blockcode/gui-iotbit",a=(r)=>[{id:"init",text:n(o,{id:"blocks.stepmotor.init",defaultMessage:"set pins INA:[INA] INB:[INB] INC:[INC] IND:[IND]"}),inputs:{INA:r.boardPins?{menu:r.boardPins.out,defaultValue:p(r)?"18":"1"}:{type:"positive_integer",defaultValue:1},INB:r.boardPins?{menu:r.boardPins.out,defaultValue:p(r)?"19":"2"}:{type:"positive_integer",defaultValue:2},INC:r.boardPins?{menu:r.boardPins.out,defaultValue:p(r)?"21":"3"}:{type:"positive_integer",defaultValue:3},IND:r.boardPins?{menu:r.boardPins.out,defaultValue:p(r)?"5":"4"}:{type:"positive_integer",defaultValue:4}},mpy(e){let t=r.boardPins?e.getFieldValue("INA"):this.valueToCode(e,"INA",this.ORDER_NONE),s=r.boardPins?e.getFieldValue("INB"):this.valueToCode(e,"INB",this.ORDER_NONE),C=r.boardPins?e.getFieldValue("INC"):this.valueToCode(e,"INC",this.ORDER_NONE),m=r.boardPins?e.getFieldValue("IND"):this.valueToCode(e,"IND",this.ORDER_NONE);return this.definitions_.stepper_motor=`_stepper = stepper_motor.StepperMotor(${t}, ${s}, ${C}, ${m})`,""}},{id:"rpm",text:n(o,{id:"blocks.stepmotor.rpm",defaultMessage:"set rpm [RPM]"}),inputs:{RPM:{shadow:"rpmSlider",defaultValue:10}},mpy(e){return`_stepper.rpm = ${this.valueToCode(e,"RPM",this.ORDER_NONE)}
`}},{id:"rpmSlider",shadow:!0,output:"number",inputs:{RPM:{type:"slider",defaultValue:0,min:0,max:20}},mpy(e){return[e.getFieldValue("RPM")||0,this.ORDER_NONE]}},{id:"right",text:n(o,{id:"blocks.stepmotor.right",defaultMessage:"turn [IMAGE] around"}),inputs:{IMAGE:{type:"image",src:i}},mpy(e){let t="";return t+=`_stepper.forward()
`,t+=`_stepper.run()
`,t}},{id:"left",text:n(o,{id:"blocks.stepmotor.left",defaultMessage:"turn [IMAGE] around"}),inputs:{IMAGE:{type:"image",src:l}},mpy(e){let t="";return t+=`_stepper.backward()
`,t+=`_stepper.run()
`,t}},{id:"stop",text:n(o,{id:"blocks.stepmotor.stop",defaultMessage:"stop"}),mpy(e){return`_stepper.stop()
`}},"---",{id:"turnRightSteps",text:n(o,{id:"blocks.stepmotor.turnRightSteps",defaultMessage:"turn [IMAGE][STEPS] steps"}),inputs:{IMAGE:{type:"image",src:i},STEPS:{type:"integer",defaultValue:10}},mpy(e){let t=this.valueToCode(e,"STEPS",this.ORDER_NONE),s="";return s+=`_stepper.move(${t})
`,s+=`await _stepper.run_wait()
`,s}},{id:"turnLeftSteps",text:n(o,{id:"blocks.stepmotor.turnLeftSteps",defaultMessage:"turn [IMAGE][STEPS] steps"}),inputs:{IMAGE:{type:"image",src:l},STEPS:{type:"integer",defaultValue:10}},mpy(e){let t=this.valueToCode(e,"STEPS",this.ORDER_NONE),s="";return s+=`_stepper.move(-${t})
`,s+=`await _stepper.run_wait()
`,s}},"---",{id:"turnRight",text:n(o,{id:"blocks.stepmotor.turnRight",defaultMessage:"turn [IMAGE][DEGREES] degrees"}),inputs:{IMAGE:{type:"image",src:i},DEGREES:{type:"integer",defaultValue:15}},mpy(e){let t=this.valueToCode(e,"DEGREES",this.ORDER_NONE),s="";return s+=`_stepper.rotate(${t})
`,s+=`await _stepper.run_wait()
`,s}},{id:"turnLeft",text:n(o,{id:"blocks.stepmotor.turnLeft",defaultMessage:"trun [IMAGE][DEGREES] degrees"}),inputs:{IMAGE:{type:"image",src:l},DEGREES:{type:"integer",defaultValue:15}},mpy(e){let t=this.valueToCode(e,"DEGREES",this.ORDER_NONE),s="";return s+=`_stepper.rotate(-${t})
`,s+=`await _stepper.run_wait()
`,s}},{id:"turn",text:n(o,{id:"blocks.stepmotor.turn",defaultMessage:"turn to [ANGLE] degrees"}),inputs:{ANGLE:{type:"angle",defaultValue:0}},mpy(e){let t=this.valueToCode(e,"ANGLE",this.ORDER_NONE),s="";return s+=`_stepper.target_angle = ${t}
`,s+=`await _stepper.run_wait()
`,s}}],_={iotOutPins:{items:[["P0","33"],["P1","32"],["P5","0"],["P6","16"],["P7","17"],["P8","26"],["P9","25"],["P11","2"],["P13","18"],["P14","19"],["P15","21"],["P16","5"],["P19","22"],["P20","23"],["P23","27"],["P24","14"],["P25","12"],["P26","13"],["P27","15"],["P28","4"]]}};var d="./assets/stepper_motor-80vwk46z.py";var f=(r)=>{if(r.editor==="@blockcode/gui-arduino")return[];return[{name:"stepper_motor",type:"text/x-python",uri:d}]};var u={en:{"blocks.motor.name":"Motor","blocks.motor.init":"set pins INA[INA] INB[INB] INC[INC] IND[IND]","blocks.motor.rpm":"set rpm [RPM]","blocks.motor.right":"turn [IMAGE] around","blocks.motor.left":"turn [IMAGE] around","blocks.motor.stop":"stop","blocks.motor.turnRightSteps":"turn [IMAGE][STEPS] steps","blocks.motor.turnLeftSteps":"turn [IMAGE][STEPS] steps","blocks.motor.turnRight":"turn [IMAGE][DEGREES] degrees","blocks.motor.turnLeft":"trun [IMAGE][DEGREES] degrees","blocks.motor.turn":"turn to [ANGLE] degrees"},"zh-Hans":{"blocks.motor.name":"电机","blocks.motor.init":"初始引腳引脚 INA[INA] INB[INB] INC[INC] IND[IND]","blocks.motor.rpm":"将转速设为[RPM]RPM","blocks.motor.right":"连续右转[IMAGE]","blocks.motor.left":"连续左转[IMAGE]","blocks.motor.stop":"停止","blocks.motor.turnRightSteps":"右转[IMAGE][STEPS]步","blocks.motor.turnLeftSteps":"左转[IMAGE][STEPS]步","blocks.motor.turnRight":"右转[IMAGE][DEGREES]度","blocks.motor.turnLeft":"左转[IMAGE][DEGREES]度","blocks.motor.turn":"转到[ANGLE]度"},"zh-Hant":{"blocks.motor.name":"電機","blocks.motor.init":"初始引腳引腳 INA[INA] INB[INB] INC[INC] IND[IND]","blocks.motor.rpm":"將轉速設為[RPM]RPM","blocks.motor.right":"連續右轉[IMAGE]","blocks.motor.left":"連續左轉[IMAGE]","blocks.motor.stop":"停止","blocks.motor.turnRightSteps":"右轉[IMAGE][STEPS]步","blocks.motor.turnLeftSteps":"左轉[IMAGE][STEPS]步","blocks.motor.turnRight":"右轉[IMAGE][DEGREES]度","blocks.motor.turnLeft":"左轉[IMAGE][DEGREES]度","blocks.motor.turn":"轉到[ANGLE]度"}};var c="./assets/icon-v5jfq71g.svg";import{jsx as L}from"preact/jsx-runtime";h(u);var F={icon:c,name:L(I,{id:"blocks.stepmotor.name",defaultMessage:"28BYJ-48 Stepper"}),files:f,blocks:a,menus:_};export{F as default};
