import{addLocalesMessages as N,Text as M}from"@blockcode/core";import{Text as n}from"@blockcode/core";import{jsx as d}from"preact/jsx-runtime";var u=(i)=>[{id:"init",text:d(n,{id:"blocks.motor.init",defaultMessage:"set [MOTOR] pins IN1:[IN1] IN2:[IN2]"}),inputs:{MOTOR:{menu:"Motor"},IN1:i.boardPins?{menu:i.boardPins.pwm}:{type:"positive_integer",defaultValue:1},IN2:i.boardPins?{menu:i.boardPins.pwm}:{type:"positive_integer",defaultValue:2}},ino(o){let e=o.getFieldValue("MOTOR"),t=i.boardPins?o.getFieldValue("IN1"):this.valueToCode(o,"IN1",this.ORDER_NONE),r=i.boardPins?o.getFieldValue("IN2"):this.valueToCode(o,"IN2",this.ORDER_NONE);return this.definitions_[`variable_${e}`]=`uint8_t _${e}[] = {${t}, ${r}};`,this.definitions_[`setup_pin_${t}`]=`pinMode(_${e}[0], OUTPUT);`,this.definitions_[`setup_pin_${r}`]=`pinMode(_${e}[1], OUTPUT);`,""},mpy(o){let e=o.getFieldValue("MOTOR"),t=i.boardPins?o.getFieldValue("IN1"):this.valueToCode(o,"IN1",this.ORDER_NONE),r=i.boardPins?o.getFieldValue("IN2"):this.valueToCode(o,"IN2",this.ORDER_NONE);return this.definitions_.import_pin="from machine import Pin",this.definitions_.import_pwm="from machine import PWM",this.definitions_[`motor_${e}`]=`_${e} = (PWM(Pin(${t}), freq=1000), PWM(Pin(${r}), freq=1000))`,""}},{id:"run",text:d(n,{id:"blocks.motor.run",defaultMessage:"set [MOTOR] to [SPEED] % [DIR] speed"}),inputs:{MOTOR:{menu:"Motor"},SPEED:{shadow:"speedvalue"},DIR:{type:"number",inputMode:!0,defaultValue:"1",menu:[[d(n,{id:"blocks.motor.forward",defaultMessage:"forward"}),"1"],[d(n,{id:"blocks.motor.reverse",defaultMessage:"reverse"}),"-1"]]}},ino(o){let e=o.getFieldValue("MOTOR"),t=this.valueToCode(o,"DIR",this.ORDER_NONE),r=this.valueToCode(o,"SPEED",this.ORDER_NONE),s="";if(t>0)s+=`analogWrite(_${e}[0], round((float)${r} * 2.55));
`,s+=`analogWrite(_${e}[1], 0);
`;else s+=`analogWrite(_${e}[0], 0);
`,s+=`analogWrite(_${e}[1], round((float)${r} * 2.55));
`;return s},mpy(o){let e=o.getFieldValue("MOTOR"),t=this.valueToCode(o,"DIR",this.ORDER_NONE),r=this.valueToCode(o,"SPEED",this.ORDER_NONE),s="";if(t>0)s+=`_${e}[0].duty(round(${r} * 10.23))
`,s+=`_${e}[1].duty(0)
`;else s+=`_${e}[0].duty(0)
`,s+=`_${e}[1].duty(round(${r} * 10.23))
`;return s}},{id:"stop",text:d(n,{id:"blocks.motor.stop",defaultMessage:"stop [MOTOR]"}),inputs:{MOTOR:{menu:"Motor"}},ino(o){let e=o.getFieldValue("MOTOR"),t="";return t+=`analogWrite(_${e}[0], 255);
`,t+=`analogWrite(_${e}[1], 255);
`,t},mpy(o){let e=o.getFieldValue("MOTOR"),t="";return t+=`_${e}[0].duty(255)
`,t+=`_${e}[1].duty(255)
`,t}},{id:"speedvalue",shadow:!0,output:"number",inputs:{SPEED:{type:"slider",defaultValue:100,min:0,max:100}},mpy(o){return[o.getFieldValue("SPEED")||0]},ino(o){return[o.getFieldValue("SPEED")||0]}}],a={Motor:{items:["M1","M2","M3","M4"]}};var l={en:{"blocks.motor.name":"Motor","blocks.motor.init":"set [MOTOR] pins IN1:[IN1] IN2:[IN2]","blocks.motor.run":"set [MOTOR] to [SPEED] % [DIR] speed","blocks.motor.forward":"forward","blocks.motor.reverse":"reverse","blocks.motor.stop":"stop [MOTOR]"},"zh-Hans":{"blocks.motor.name":"电机","blocks.motor.init":"初始 [MOTOR] 引脚 IN1:[IN1] IN2:[IN2]","blocks.motor.run":"将 [MOTOR] [DIR] 速度设为 [SPEED] %","blocks.motor.forward":"正转","blocks.motor.reverse":"反转","blocks.motor.stop":"停止 [MOTOR]"},"zh-Hant":{"blocks.motor.name":"電機","blocks.motor.init":"初始 [MOTOR] 引腳 IN1:[IN1] IN2:[IN2]","blocks.motor.run":"將 [MOTOR] [DIR] 速度設為 [SPEED] %","blocks.motor.forward":"正轉","blocks.motor.reverse":"反轉","blocks.motor.stop":"停止 [MOTOR]"}};var m="./assets/icon-88gsk5af.png";import{jsx as p}from"preact/jsx-runtime";N(l);var h={icon:m,name:p(M,{id:"blocks.motor.name",defaultMessage:"Motor"}),blocks:u,menus:a};export{h as default};
