en:
  blocks.brain.name: Brain
  blocks.brain.openplatform: iFLYTEK Open Platform authorization
  blocks.brain.openplatform.description1: 'Please register your own '
  blocks.brain.openplatform.description2: iFLYTEK Open Platform (Chinese)
  blocks.brain.openplatform.description3: ' account, the test account we provide does not guarantee that every request will be successful.'
  blocks.brain.addPrompt: add prompt [PROMPT] to Brain
  blocks.brain.prompt: dialogue with the character of a cat
  blocks.brain.clearHistory: delete all history
  blocks.brain.askQuestion: ask Brain [QUESTION] and wait
  blocks.brain.question: hello
  blocks.brain.answer: answer

zh-Hans:
  blocks.brain.name: 智脑
  blocks.brain.openplatform: 讯飞开放平台认证信息
  blocks.brain.openplatform.description1: 请注册您自己的
  blocks.brain.openplatform.description2: 讯飞开放平台
  blocks.brain.openplatform.description3: 账号，我们提供的测试账号不保证每次请求都成功。
  blocks.brain.addPrompt: 将指令说明 [PROMPT] 加入智脑
  blocks.brain.prompt: 用一只猫的性格对话
  blocks.brain.clearHistory: 删除所有历史记录
  blocks.brain.askQuestion: 询问智脑 [QUESTION] 并等待
  blocks.brain.question: 你好
  blocks.brain.answer: 回答

zh-Hant:
  blocks.brain.name: 智腦
  blocks.brain.openplatform: 訊飛開放平台認證信息
  blocks.brain.openplatform.description1: 請註冊您自己的
  blocks.brain.openplatform.description2: 訊飛開放平台
  blocks.brain.openplatform.description3: 賬號，我們提供的測試賬號不保證每次請求都成功。
  blocks.brain.addPrompt: 將指令說明 [PROMPT] 加入智腦
  blocks.brain.prompt: 用一隻貓的性格對話
  blocks.brain.clearHistory: 刪除所有歷史記錄
  blocks.brain.askQuestion: 詢問智腦 [QUESTION] 並等待
  blocks.brain.question: 你好
  blocks.brain.answer: 回答
