import{addLocalesMessages as I,Text as w}from"@blockcode/core";import{changeCase as u}from"@blockcode/utils";import{Text as n}from"@blockcode/core";import{jsx as f}from"preact/jsx-runtime";var k=(l)=>[l.editor==="@blockcode/gui-arduino"&&{id:"eventPolling",text:f(n,{id:"blocks.switchkey.eventPolling",defaultMessage:"manual event polling"}),ino(e){return this.definitions_.declare__1buttonTicks="void _1buttonTicks();",this.definitions_._1buttonTicks=`void _1buttonTicks() {
}`,`_1buttonTicks();
`}},"---",{id:"whenKey",text:f(n,{id:"blocks.switchkey.whenKey",defaultMessage:"when pin [PIN] [STATE]"}),hat:!0,inputs:{PIN:l.boardPins?{menu:l.boardPins.in}:{type:"positive_integer",defaultValue:"1"},STATE:{menu:"StateOption"}},ino(e){let _=l.boardPins?e.getFieldValue("PIN"):this.valueToCode(e,"PIN",this.ORDER_NONE),t=e.getFieldValue("STATE"),s=`_1button_${_}`;if(this.definitions_._1buttonTicks)this.definitions_._1buttonTicks=this.definitions_._1buttonTicks.replace(`
}`,`
  ${s}.tick();
}`);else this.definitions_[`tick_${s}`]=`${s}.tick();`;this.definitions_.include_onebutton="#include <OneButton.h>",this.definitions_[`variable_${s}`]=`OneButton ${s}(${_});`;let i=`${s}_${t}`,c=this.statementToCode(e)||"";this.definitions_[`declare_${i}`]=`void ${i}();`,this.definitions_[i]=`void ${i}() {
${c}}`,this.definitions_[`setup_${i}`]=`${s}.attach${t}(${i});`},mpy(e){let _=l.boardPins?e.getFieldValue("PIN"):this.valueToCode(e,"PIN",this.ORDER_NONE),t=u.snakeCase(e.getFieldValue("STATE")),s=`_1button_${_}`;this.definitions_.import_onebutton="from onebutton import OneButton",this.definitions_[s]=`${s} = OneButton(${_})`;let i=this.createName("_1button_flag");this.definitions_[i]=`${i} = asyncio.ThreadSafeFlag()`;let c=this.statementToCode(e)||"",r="";r+=`while True:
`,r+=`${this.INDENT}await ${i}.wait()
`,r+=c;let y=this.createName(`${s}_${t}`);c=this.prefixLines(r,this.INDENT),c=this.addEventTrap(c,"1button_callback"),r=`@_tasks__.append
`,r+=c,r+=`${s}.on_${t}(lambda: ${i}.set())
`,this.definitions_[y]=r}},{id:"keyState",text:f(n,{id:"blocks.switchkey.keyState",defaultMessage:"pin [PIN] is pressed?"}),output:"boolean",inputs:{PIN:l.boardPins?{menu:l.boardPins.in}:{type:"positive_integer",defaultValue:"1"}},ino(e){return[`(digitalRead(${l.boardPins?e.getFieldValue("PIN"):this.valueToCode(e,"PIN",this.ORDER_NONE)}) == LOW)`,this.ORDER_ATOMIC]},mpy(e){let _=l.boardPins?e.getFieldValue("PIN"):this.valueToCode(e,"PIN",this.ORDER_NONE),t=`_1button_${_}`;return this.definitions_.import_onebutton="from onebutton import OneButton",this.definitions_[t]=`${t} = OneButton(${_})`,[`${t}.is_pressed()`,this.ORDER_FUNCTION_CALL]}}].filter(Boolean),o={StateOption:{items:[[f(n,{id:"blocks.switchkey.keyClick",defaultMessage:"click"}),"Click"],[f(n,{id:"blocks.switchkey.keyDoubleClick",defaultMessage:"doubel click"}),"DoubleClick"],[f(n,{id:"blocks.switchkey.keyLongPressed",defaultMessage:"long pressed"}),"LongPressStart"],[f(n,{id:"blocks.switchkey.keyDuringLongPressed",defaultMessage:"long pressed (during)"}),"DuringLongPress"]]}};var a={en:{"blocks.switchkey.name":"Key Input","blocks.switchkey.eventPolling":"manual button event polling","blocks.switchkey.whenKey":"when pin [PIN] [STATE]","blocks.switchkey.keyState":"pin [PIN] is pressed?","blocks.switchkey.keyPressed":"pressed","blocks.switchkey.keyClick":"click","blocks.switchkey.keyDoubleClick":"doubel click","blocks.switchkey.keyLongPressed":"long pressed","blocks.switchkey.keyDuringLongPressed":"long pressed (during)"},"zh-Hans":{"blocks.switchkey.name":"按键输入","blocks.switchkey.eventPolling":"手动按键事件轮询","blocks.switchkey.whenKey":"当引脚 [PIN] 被 [STATE]","blocks.switchkey.keyState":"按下引脚 [PIN]？","blocks.switchkey.keyClick":"单击","blocks.switchkey.keyDoubleClick":"双击","blocks.switchkey.keyLongPressed":"长按","blocks.switchkey.keyDuringLongPressed":"长按（持续）"},"zh-Hant":{"blocks.switchkey.name":"按鍵輸入","blocks.switchkey.eventPolling":"手動按鍵事件輪詢","blocks.switchkey.whenKey":"當引腳 [PIN] 被 [STATE]","blocks.switchkey.keyState":"按下引腳 [PIN]？","blocks.switchkey.keyClick":"單擊","blocks.switchkey.keyDoubleClick":"雙擊","blocks.switchkey.keyLongPressed":"長按","blocks.switchkey.keyDuringLongPressed":"長按（持續）"}};var d="./assets/icon-3d98sx44.png";var p="./assets/onebutton-qdw4a1gg.py";import{jsx as E}from"preact/jsx-runtime";I(a);var T={icon:d,name:E(w,{id:"blocks.switchkey.name",defaultMessage:"Key Input"}),files(l){if(l.editor!=="@blockcode/gui-arduino")return[{name:"onebutton",common:!0,type:"text/x-python",uri:p}];return[]},blocks:k,menus:o};export{T as default};
