import{addLocalesMessages as y,Text as N}from"@blockcode/core";import{changeCase as p}from"@blockcode/utils";import{Text as c}from"@blockcode/core";import{jsx as a}from"preact/jsx-runtime";var r=(t)=>[t.editor==="@blockcode/gui-arduino"&&{id:"eventPolling",text:a(c,{id:"blocks.switchkey.eventPolling",defaultMessage:"button events polling"}),ino(e){return this.definitions_.declare__1buttonTicks="void _1buttonTicks();",this.definitions_._1buttonTicks=`void _1buttonTicks() {
}`,`_1buttonTicks();
`}},"---",{id:"whenKey",text:a(c,{id:"blocks.switchkey.whenKey",defaultMessage:"when pin [PIN] [STATE]"}),hat:!0,inputs:{PIN:t.boardPins?{menu:t.boardPins.in}:{type:"positive_integer",defaultValue:"1"},STATE:{menu:"StateOption"}},ino(e){let n=t.boardPins?e.getFieldValue("PIN"):this.valueToCode(e,"PIN",this.ORDER_NONE),i=e.getFieldValue("STATE"),l=`_1button_${n}`,_="_1buttonTicks";if(!this.definitions_._1buttonTicks)this.definitions_.declare__1buttonTicks="void _1buttonTicks();",this.definitions_._1buttonTicks=`void _1buttonTicks() {
}`;this.definitions_._1buttonTicks=this.definitions_._1buttonTicks.replace(`
}`,`
  ${l}.tick();
}`),this.definitions_.include_onebutton="#include <OneButton.h>",this.definitions_[`variable_${l}`]=`OneButton ${l}(${n});`;let s=`${l}_${i}`,o=this.statementToCode(e)||"";this.definitions_[`declare_${s}`]=`void ${s}();`,this.definitions_[s]=`void ${s}() {
${o}}`,this.definitions_[`setup_${s}`]=`${l}.attach${i}(${s});`},mpy(e){let n=t.boardPins?e.getFieldValue("PIN"):this.valueToCode(e,"PIN",this.ORDER_NONE),i=p.snakeCase(e.getFieldValue("STATE")),l=`_1button_${n}`;this.definitions_.import_onebutton="from onebutton import OneButton",this.definitions_[l]=`${l} = OneButton(${n})`;let _=this.createName("_1button_flag");this.definitions_[_]=`${_} = asyncio.ThreadSafeFlag()`;let s=this.statementToCode(e)||"",o="";o+=`while True:
`,o+=`${this.INDENT}await ${_}.wait()
`,o+=s;let b=this.createName(`${l}_${i}`);s=this.prefixLines(o,this.INDENT),s=this.addEventTrap(s,"1button_callback"),o=`@_tasks__.append
`,o+=s,o+=`${l}.on_${i}(lambda: ${_}.set())
`,this.definitions_[b]=o}},{id:"keyState",text:a(c,{id:"blocks.switchkey.keyState",defaultMessage:"pin [PIN] is pressed?"}),output:"boolean",inputs:{PIN:t.boardPins?{menu:t.boardPins.in}:{type:"positive_integer",defaultValue:"1"}},ino(e){return[`(digitalRead(${t.boardPins?e.getFieldValue("PIN"):this.valueToCode(e,"PIN",this.ORDER_NONE)}) == LOW)`,this.ORDER_ATOMIC]},mpy(e){let n=t.boardPins?e.getFieldValue("PIN"):this.valueToCode(e,"PIN",this.ORDER_NONE),i=`_1button_${n}`;return this.definitions_.import_onebutton="from onebutton import OneButton",this.definitions_[i]=`${i} = OneButton(${n})`,[`${i}.is_pressed()`,this.ORDER_FUNCTION_CALL]}}],f={StateOption:{items:[[a(c,{id:"blocks.switchkey.keyClick",defaultMessage:"click"}),"Click"],[a(c,{id:"blocks.switchkey.keyDoubleClick",defaultMessage:"doubel click"}),"DoubleClick"],[a(c,{id:"blocks.switchkey.keyLongPressed",defaultMessage:"long pressed"}),"LongPressStart"],[a(c,{id:"blocks.switchkey.keyDuringLongPressed",defaultMessage:"long pressed (during)"}),"DuringLongPress"]]}};var d={en:{"blocks.switchkey.name":"Key Input","blocks.switchkey.eventPolling":"button events polling","blocks.switchkey.whenKey":"when pin [PIN] [STATE]","blocks.switchkey.keyState":"pin [PIN] is pressed?","blocks.switchkey.keyPressed":"pressed","blocks.switchkey.keyClick":"click","blocks.switchkey.keyDoubleClick":"doubel click","blocks.switchkey.keyLongPressed":"long pressed","blocks.switchkey.keyDuringLongPressed":"long pressed (during)"},"zh-Hans":{"blocks.switchkey.name":"按键输入","blocks.switchkey.eventPolling":"按键事件轮询","blocks.switchkey.whenKey":"当引脚 [PIN] 被 [STATE]","blocks.switchkey.keyState":"按下引脚 [PIN]？","blocks.switchkey.keyClick":"单击","blocks.switchkey.keyDoubleClick":"双击","blocks.switchkey.keyLongPressed":"长按","blocks.switchkey.keyDuringLongPressed":"长按（持续）"},"zh-Hant":{"blocks.switchkey.name":"按鍵輸入","blocks.switchkey.eventPolling":"按鍵事件輪詢","blocks.switchkey.whenKey":"當引腳 [PIN] 被 [STATE]","blocks.switchkey.keyState":"按下引腳 [PIN]？","blocks.switchkey.keyClick":"單擊","blocks.switchkey.keyDoubleClick":"雙擊","blocks.switchkey.keyLongPressed":"長按","blocks.switchkey.keyDuringLongPressed":"長按（持續）"}};var k="./assets/icon-3d98sx44.png";var u="./assets/onebutton-qdw4a1gg.py";import{jsx as P}from"preact/jsx-runtime";y(d);var v={icon:k,name:P(N,{id:"blocks.switchkey.name",defaultMessage:"Key Input"}),files(t){if(t.editor!=="@blockcode/gui-arduino")return[{name:"onebutton",common:!0,type:"text/x-python",uri:u}];return[]},blocks:r,menus:f};export{v as default};
