import{addLocalesMessages as O,Text as N}from"@blockcode/core";import{Color as d,MathUtils as p}from"@blockcode/utils";function g(e,o){return e.on("start",()=>{let t=new o.Group({id:"pen_renderer"});e.paintLayer.add(t)}),e.targetUtils.on("update",(t)=>{let s=e.querySelector("#pen_renderer"),a=e.getData(t,"pen.position");if(!s||!a)return;let n=t.position();if(Math.floor(a.x)===Math.floor(n.x)&&Math.floor(a.y)===Math.floor(n.y))return;let c=new o.Line({points:[a.x,a.y,n.x,n.y],stroke:e.getData(t,"pen.color")??"#FF0000",strokeWidth:e.getData(t,"pen.size")??1,lineJoin:"round",lineCap:"round"});s.add(c),e.setData(t,"pen.position",n)}),{get key(){return"pen"},get renderer(){return e.querySelector("#pen_renderer")},erase(){if(!this.renderer)return;this.renderer.destroyChildren()},async stamp(t){if(!this.renderer)return;while(t.getAttr("_frameIndex")!=null)await e.nextTick();let s=t.clone({id:null,name:null,visible:!0});this.renderer.add(s)},down(t){e.setData(t,"pen.position",t.position())},up(t){e.setData(t,"pen.position",null)},setColor(t,s){e.setData(t,"pen.color",s)},addColorParam(t,s,a){let n=p.toNumber(a),c=e.getData(t,"pen.color")??"#FF0000",l=new d(c).toHSVColor();switch(s){case"saturation":l.hsv.s+=n;break;case"brightness":l.hsv.v+=n;break;case"hub":default:l.hsv.h+=n*3.6}e.setData(t,"pen.color",l.hex)},setColorParam(t,s,a){let n=p.toNumber(a),c=e.getData(t,"pen.color")??"#FF0000",l=new d(c).toHSVColor();switch(s){case"saturation":l.hsv.s=n;break;case"brightness":l.hsv.v=n;break;case"hub":default:l.hsv.h=n*3.6}e.setData(t,"pen.color",l.hex)},setSize(t,s){let a=p.toNumber(s);e.setData(t,"pen.size",a)},addSize(t,s){let a=p.toNumber(s),n=e.getData(t,"pen.size")??1;e.setData(t,"pen.size",n+a)}}}import{Text as r}from"@blockcode/core";import{jsx as i}from"preact/jsx-runtime";var u=[{id:"erase",text:i(r,{id:"blocks.pen.erase",defaultMessage:"erase all"}),emu(e){return`runtime.extensions.pen.erase();
`},mpy(e){return`pen.clear()
`}},{id:"stamp",text:i(r,{id:"blocks.pen.stamp",defaultMessage:"stamp"}),forStage:!1,emu(e){return`await runtime.extensions.pen.stamp(target);
`},mpy(e){return`pen.stamp(target)
`}},{id:"down",text:i(r,{id:"blocks.pen.down",defaultMessage:"pen down"}),forStage:!1,emu(e){return`runtime.extensions.pen.down(target);
`},mpy(e){return`pen.down(target)
`}},{id:"up",text:i(r,{id:"blocks.pen.up",defaultMessage:"pen up"}),forStage:!1,emu(e){return`runtime.extensions.pen.up(target);
`},mpy(e){return`pen.up(target)
`}},{id:"penColor",text:i(r,{id:"blocks.pen.penColor",defaultMessage:"set pen color to [COLOR]"}),forStage:!1,inputs:{COLOR:{type:"color"}},emu(e){return`runtime.extensions.pen.setColor(target, ${this.valueToCode(e,"COLOR",this.ORDER_NONE)||'"#ff0000"'});
`},mpy(e){return`pen.set_color(target, ${this.valueToCode(e,"COLOR",this.ORDER_NONE)||"(255, 0, 0)"})
`}},{id:"changePen",text:i(r,{id:"blocks.pen.changePen",defaultMessage:"change pen [OPTION] by [VALUE]"}),forStage:!1,inputs:{OPTION:{menu:"colorParam"},VALUE:{type:"number",defaultValue:10}},emu(e){let o=this.valueToCode(e,"OPTION",this.ORDER_NONE),t=this.valueToCode(e,"VALUE",this.ORDER_NONE)||10;return`runtime.extensions.pen.addColorParam(target, '${o}', ${t});
`},mpy(e){let o=this.valueToCode(e,"OPTION",this.ORDER_NONE),t=this.valueToCode(e,"VALUE",this.ORDER_NONE)||10;return`pen.change_color(target, ${o}=${t})
`}},{id:"setPen",text:i(r,{id:"blocks.pen.setPen",defaultMessage:"set pen [OPTION] to [VALUE]"}),forStage:!1,inputs:{OPTION:{menu:"colorParam"},VALUE:{type:"number",defaultValue:50}},emu(e){let o=this.valueToCode(e,"OPTION",this.ORDER_NONE),t=this.valueToCode(e,"VALUE",this.ORDER_NONE)||"0";return`runtime.extensions.pen.setColorParam(target, '${o}', ${t});
`},mpy(e){let o=this.valueToCode(e,"OPTION",this.ORDER_NONE),t=this.valueToCode(e,"VALUE",this.ORDER_NONE)||"0";return`pen.set_color(target, ${o}=${t})
`}},{id:"changeSize",text:i(r,{id:"blocks.pen.changeSize",defaultMessage:"change pen size by [SIZE]"}),forStage:!1,inputs:{SIZE:{type:"number",defaultValue:1}},emu(e){return`runtime.extensions.pen.addSize(target, ${this.valueToCode(e,"SIZE",this.ORDER_NONE)||"1"});
`},mpy(e){return`pen.change_size(target, ${this.valueToCode(e,"SIZE",this.ORDER_NONE)||"1"})
`}},{id:"setSize",text:i(r,{id:"blocks.pen.setSize",defaultMessage:"set pen size to [SIZE]"}),forStage:!1,inputs:{SIZE:{type:"number",defaultValue:1}},emu(e){return`runtime.extensions.pen.setSize(target, ${this.valueToCode(e,"SIZE",this.ORDER_NONE)||"1"});
`},mpy(e){return`pen.set_size(target, ${this.valueToCode(e,"SIZE",this.ORDER_NONE)||"1"})
`}}],h={colorParam:{inputMode:!0,defaultValue:"hue",items:[[i(r,{id:"blocks.pen.color",defaultMessage:"color"}),"hue"],[i(r,{id:"blocks.pen.saturation",defaultMessage:"saturation"}),"saturation"],[i(r,{id:"blocks.pen.brightness",defaultMessage:"brightness"}),"brightness"]]}};var b={en:{"blocks.pen.name":"Pen","blocks.pen.erase":"erase all","blocks.pen.stamp":"stamp","blocks.pen.down":"pen down","blocks.pen.up":"pen up","blocks.pen.penColor":"set pen color to [COLOR]","blocks.pen.color":"color","blocks.pen.saturation":"saturation","blocks.pen.brightness":"brightness","blocks.pen.changePen":"change pen [OPTION] by [VALUE]","blocks.pen.setPen":"set pen [OPTION] to [VALUE]","blocks.pen.changeSize":"change pen size by [SIZE]","blocks.pen.setSize":"set pen size to [SIZE]"},"zh-Hans":{"blocks.pen.name":"画笔","blocks.pen.erase":"全部擦除","blocks.pen.stamp":"图章","blocks.pen.down":"落笔","blocks.pen.up":"抬笔","blocks.pen.penColor":"将笔的颜色设为 [COLOR]","blocks.pen.color":"颜色","blocks.pen.saturation":"饱和度","blocks.pen.brightness":"亮度","blocks.pen.changePen":"将笔的 [OPTION] 增加 [VALUE]","blocks.pen.setPen":"将笔的 [OPTION] 设为 [VALUE]","blocks.pen.changeSize":"将笔的粗细增加 [SIZE]","blocks.pen.setSize":"将笔的粗细设为 [SIZE]"},"zh-Hant":{"blocks.pen.name":"畫筆","blocks.pen.erase":"全部擦除","blocks.pen.stamp":"圖章","blocks.pen.down":"落筆","blocks.pen.up":"抬筆","blocks.pen.penColor":"將筆的顏色設為 [COLOR]","blocks.pen.color":"顏色","blocks.pen.saturation":"飽和度","blocks.pen.brightness":"亮度","blocks.pen.changePen":"將筆的 [OPTION] 增加 [VALUE]","blocks.pen.setPen":"將筆的 [OPTION] 設為 [VALUE]","blocks.pen.changeSize":"將筆的粗細增加 [SIZE]","blocks.pen.setSize":"將筆的粗細設為 [SIZE]"}};var _="./assets/icon-wkgstzvn.svg";var m="./assets/pen-58a1wpz7.py";import{jsx as k}from"preact/jsx-runtime";O(b);var M={icon:_,name:k(N,{id:"blocks.pen.name",defaultMessage:"Pen"}),files:[{name:"pen",type:"text/x-python",uri:m}],emulator:g,blocks:u,menus:h};export{M as default};
