import{addLocalesMessages as R,Text as $}from"@blockcode/core";var p="./assets/codexpad-p382s984.mpy";var l="./assets/__init__-4jpmpkwq.mpy";var Q="./assets/central-94j8tygt.mpy";var D="./assets/client-wbrb6dsj.mpy";var u="./assets/core-c2cvjx0k.mpy";var Y="./assets/device-6ks28bfy.mpy";var h="./assets/security-7amdp9gq.mpy";var m=[{name:"codexpad.mpy",type:"text/x-python",uri:p},{common:!0,name:"aioble/__init__.mpy",type:"text/x-python",uri:l},{common:!0,name:"aioble/central.mpy",type:"text/x-python",uri:Q},{common:!0,name:"aioble/client.mpy",type:"text/x-python",uri:D},{common:!0,name:"aioble/core.mpy",type:"text/x-python",uri:u},{common:!0,name:"aioble/device.mpy",type:"text/x-python",uri:Y},{common:!0,name:"aioble/security.mpy",type:"text/x-python",uri:h}];import{Text as _}from"@blockcode/core";import{ScratchBlocks as n}from"@blockcode/blocks";import{jsx as d}from"preact/jsx-runtime";var T=(t)=>{if(!t.definitions_.codexpad_update){let e="";e+=`@_tasks__.append
`,e+=`async def codexpad_update():
`,e+=`  while True:
`,e+=`    await codex_pad.update()
`,e+=`    await asyncio.sleep_ms(5)
`,t.definitions_.codexpad_update=e}},r={KEYS:{items:[[n.Msg.EVENT_WHENKEYPRESSED_UP,"UP"],[n.Msg.EVENT_WHENKEYPRESSED_DOWN,"DOWN"],[n.Msg.EVENT_WHENKEYPRESSED_LEFT,"LEFT"],[n.Msg.EVENT_WHENKEYPRESSED_RIGHT,"RIGHT"],["X (□)","SQUARE_X"],["Y (△)","TRIANGLE_Y"],["A (✕)","CROSS_A"],["B (○)","CIRCLE_B"],["L1","L1"],["L2","L2"],["L3","L3"],["R1","R1"],["R2","R2"],["R3","R3"],["SELECT","SELECT"],["START","START"],["HOME","HOME"]]},JOYSTICK:{items:[[d(_,{id:"blocks.codexpad.joystickLXAxis",defaultMessage:"left joystick X"}),"LEFT_STICK_X"],[d(_,{id:"blocks.codexpad.joystickLYAxis",defaultMessage:"left joystick Y"}),"LEFT_STICK_Y"],[d(_,{id:"blocks.codexpad.joystickRXAxis",defaultMessage:"right joystick X"}),"RIGHT_STICK_X"],[d(_,{id:"blocks.codexpad.joystickRYAxis",defaultMessage:"right joystick Y"}),"RIGHT_STICK_Y"]]}},C=[{id:"connect",text:d(_,{id:"blocks.codexpad.connect",defaultMessage:"connect CodexPad with mac:[MAC]"}),inputs:{MAC:{type:"string",defaultValue:""}},mpy(t){let e=this.valueToCode(t,"MAC",this.ORDER_NONE);return this.definitions_.import_asyncio="import asyncio",this.definitions_.codexpad="codex_pad = codexpad.CodexPad()",`asyncio.create_task(codex_pad.connect(${e}, timeout_ms=60_000))
`}},{id:"scanConnect",text:d(_,{id:"blocks.codexpad.scanConnect",defaultMessage:"connect CodexPad with [BTNA] and [BTNB] combo"}),inputs:{BTNA:{menu:"KEYS",defaultValue:"START"},BTNB:{menu:[["",""]].concat(r.KEYS.items)}},mpy(t){let e=t.getFieldValue("BTNA"),o=t.getFieldValue("BTNB"),a=[`codexpad.BUTTON_${e}`];if(o)a.push(`codexpad.BUTTON_${o}`);this.definitions_.import_asyncio="import asyncio",this.definitions_.codexpad="codex_pad = codexpad.CodexPad()";let c="";return c+=`for _ in range(10):
`,c+=`  try:
`,c+=`    await codex_pad.scan_and_connect(${a.join("|")}, scan_duration_ms=1000, connect_timeout_ms=5000)
`,c+=`  except:
`,c+=`    await asyncio.sleep(1)
`,c+=`    continue
`,c+="  break;",c}},{id:"paLevel",text:d(_,{id:"blocks.codexpad.paLevel",defaultMessage:"set power amplifier level to [PA] dBm"}),inputs:{PA:{defaultValue:"0",menu:[["-16","MINUS_16"],["-12","MINUS_12"],["-8","MINUS_8"],["-5","MINUS_5"],["-3","MINUS_3"],["-1","MINUS_1"],["0","0"],["1","1"],["2","2"],["3","3"],["4","4"],["5","5"],["6","6"]]}},mpy(t){let e=t.getFieldValue("PA")||"0",o="";return o+=`await codex_pad.set_remote_tx_power(codexpad.TX_POWER_${e}_DBM)
`,o}},{id:"isConnected",text:d(_,{id:"blocks.codexpad.isconnected",defaultMessage:"CodexPad is connected?"}),output:"boolean",mpy(t){return["codex_pad.is_connected"]}},"---",{id:"whenPressed",text:d(_,{id:"blocks.codexpad.whenPressed",defaultMessage:"when [KEY] pressed"}),hat:!0,inputs:{KEY:{menu:"KEYS",defaultValue:"CROSS_A"}},mpy(t){let e=t.getFieldValue("KEY");T(this);let o=this.createName("codexpad_flag");this.definitions_[o]=`${o} = asyncio.ThreadSafeFlag()`;let a=this.statementToCode(t)||"",c="";c+=`while True:
`,c+=`  await ${o}.wait()
`,c+=a;let s=this.createName(`codexpad_${e}_pressed`);a=this.prefixLines(c,this.INDENT),a=this.addEventTrap(a,`codexpad_${e}_pressed`),c=`@_tasks__.append
`,c+=a,this.definitions_[s]=c,c=`    if codex_pad.pressed(codexpad.BUTTON_${e}): ${o}.set()
`,this.definitions_.codexpad_update+=c}},{id:"whenJoystickMoved",text:d(_,{id:"blocks.codexpad.whenJoystickMoved",defaultMessage:"when [JOYSTICK] axis [WAY] [VALUE]"}),hat:!0,inputs:{JOYSTICK:{menu:"JOYSTICK"},WAY:{menu:[">","<"]},VALUE:{type:"integer",defaultValue:150}},mpy(t){let e=t.getFieldValue("JOYSTICK"),o=t.getFieldValue("WAY"),a=this.valueToCode(t,"VALUE",this.ORDER_NONE);T(this);let c=this.createName("codexpad_flag");this.definitions_[c]=`${c} = asyncio.ThreadSafeFlag()`;let s=this.statementToCode(t)||"",i="";i+=`while True:
`,i+=`  await ${c}.wait()
`,i+=s;let y=this.createName(`codexpad_${e}_${o===">"?"greater":"less"}`);s=this.prefixLines(i,this.INDENT),s=this.addEventTrap(s,`codexpad_${e}_${o===">"?"greater":"less"}`),i=`@_tasks__.append
`,i+=s,this.definitions_[y]=i,i=`    if codex_pad._prev_inputs.axis_values[codexpad.AXIS_${e}] ${o===">"?"<=":">="} ${a} and codex_pad.axis_value(codexpad.AXIS_${e}) ${o} ${a}: ${c}.set()
`,this.definitions_.codexpad_update+=i}},"---",{id:"joystickValue",text:d(_,{id:"blocks.codexpad.joystickValue",defaultMessage:"[JOYSTICK] axis value (0~255)"}),output:"number",inputs:{JOYSTICK:{menu:"JOYSTICK"}},mpy(t){return[`codex_pad.axis_value(codexpad.AXIS_${t.getFieldValue("JOYSTICK")})`]}},{id:"keyPressed",text:d(_,{id:"blocks.codexpad.keyPressed",defaultMessage:"[KEY] is pressed"}),output:"boolean",inputs:{KEY:{menu:"KEYS",defaultValue:"CROSS_A"}},mpy(t){return[`codex_pad.pressed(codexpad.BUTTON_${t.getFieldValue("KEY")})`]}}];var x="///docs.emakefun.com/#/zh-cn/peripheral/codexpad/wireless_controller_diffrent";var B={en:{"blocks.codexpad.name":"CodexPad","blocks.codexpad.connect":"connect CodexPad with mac:[MAC]","blocks.codexpad.scanConnect":"connect CodexPad with [BTNA] and [BTNB] combo","blocks.codexpad.paLevel":"set power amplifier level to [PA] dBm","blocks.codexpad.isconnected":"CodexPad is connected?","blocks.codexpad.whenPressed":"when [KEY] pressed","blocks.codexpad.whenJoystickMoved":"when [JOYSTICK] axis [WAY] [VALUE]","blocks.codexpad.keyPressed":"[KEY] is pressed?","blocks.codexpad.joystickValue":"[JOYSTICK] axis value (0~255)","blocks.codexpad.joystickLXAxis":"left joystick X","blocks.codexpad.joystickLYAxis":"left joystick Y","blocks.codexpad.joystickRXAxis":"right joystick X","blocks.codexpad.joystickRYAxis":"right joystick Y"},"zh-Hans":{"blocks.codexpad.name":"CodexPad 手柄","blocks.codexpad.connect":"通过 CodexPad MAC:[MAC] 连接","blocks.codexpad.scanConnect":"通过 CodexPad 按键组合 [BTNA] 和 [BTNB] 连接","blocks.codexpad.paLevel":"将发射功率设为 [PA] dBm","blocks.codexpad.isconnected":"CodexPad 是否已连接？","blocks.codexpad.whenPressed":"当按下 [KEY] 时","blocks.codexpad.whenJoystickMoved":"当 [JOYSTICK] 轴值 [WAY] [VALUE] 时","blocks.codexpad.keyPressed":"[KEY] 被按下？","blocks.codexpad.joystickValue":"[JOYSTICK] 轴值（0~255）","blocks.codexpad.joystickLXAxis":"左摇杆 X","blocks.codexpad.joystickLYAxis":"左摇杆 Y","blocks.codexpad.joystickRXAxis":"右摇杆 X","blocks.codexpad.joystickRYAxis":"右摇杆 Y"},"zh-Hant":{"blocks.codexpad.name":"CodexPad 手柄","blocks.codexpad.connect":"通過 CodexPad MAC:[MAC] 連接","blocks.codexpad.scanConnect":"通過 CodexPad 按鍵組合 [BTNA] 和 [BTNB] 連接","blocks.codexpad.paLevel":"將發射功率設為 [PA] dBm","blocks.codexpad.isconnected":"CodexPad 是否已連接？","blocks.codexpad.whenPressed":"當按下 [KEY] 時","blocks.codexpad.whenJoystickMoved":"當 [JOYSTICK] 軸值 [WAY] [VALUE] 時","blocks.codexpad.keyPressed":"[KEY] 被按下？","blocks.codexpad.joystickValue":"[JOYSTICK] 軸值（0~255）","blocks.codexpad.joystickLXAxis":"左搖杆 X","blocks.codexpad.joystickLYAxis":"左搖杆 Y","blocks.codexpad.joystickRXAxis":"右搖杆 X","blocks.codexpad.joystickRYAxis":"右搖杆 Y"}};var E="./assets/icon-qzh275zn.png";import{jsx as f}from"preact/jsx-runtime";R(B);var le={icon:E,name:f($,{id:"blocks.codexpad.name",defaultMessage:"CodexPad"}),files:m,blocks:C,menus:r,readme:x};export{le as default};
