import{addLocalesMessages as g,Text as h}from"@blockcode/core";import{Text as r}from"@blockcode/core";var p="./assets/turn-left-3ncjj928.svg";var n="./assets/turn-right-ny3de90q.svg";import{jsx as o}from"preact/jsx-runtime";var l=[{id:"init",text:o(r,{id:"blocks.stepmotor.init",defaultMessage:"set pins INA[INA] INB[INB] INC[INC] IND[IND]"}),inputs:{INA:{type:"positive_integer",defaultValue:1},INB:{type:"positive_integer",defaultValue:2},INC:{type:"positive_integer",defaultValue:3},IND:{type:"positive_integer",defaultValue:4}},mpy(t){let s=this.valueToCode(t,"INA",this.ORDER_NONE),e=this.valueToCode(t,"INB",this.ORDER_NONE),d=this.valueToCode(t,"INC",this.ORDER_NONE),u=this.valueToCode(t,"IND",this.ORDER_NONE);return this.definitions_.stepper_motor=`_stepper = stepper_motor.StepperMotor(${s}, ${e}, ${d}, ${u})`,""}},{id:"rpm",text:o(r,{id:"blocks.stepmotor.rpm",defaultMessage:"set rpm [RPM]"}),inputs:{RPM:{type:"positive_integer",defaultValue:10}},mpy(t){return`_stepper.rpm = ${this.valueToCode(t,"RPM",this.ORDER_NONE)}
`}},{id:"right",text:o(r,{id:"blocks.stepmotor.right",defaultMessage:"turn [IMAGE] around"}),inputs:{IMAGE:{type:"image",src:n}},mpy(t){let s="";return s+=`_stepper.forward()
`,s+=`_stepper.run()
`,s}},{id:"left",text:o(r,{id:"blocks.stepmotor.left",defaultMessage:"turn [IMAGE] around"}),inputs:{IMAGE:{type:"image",src:p}},mpy(t){let s="";return s+=`_stepper.backward()
`,s+=`_stepper.run()
`,s}},{id:"stop",text:o(r,{id:"blocks.stepmotor.stop",defaultMessage:"stop"}),mpy(t){return`_stepper.stop()
`}},"---",{id:"turnRightSteps",text:o(r,{id:"blocks.stepmotor.turnRightSteps",defaultMessage:"turn [IMAGE][STEPS] steps"}),inputs:{IMAGE:{type:"image",src:n},STEPS:{type:"integer",defaultValue:10}},mpy(t){let s=this.valueToCode(t,"STEPS",this.ORDER_NONE),e="";return e+=`_stepper.move(${s})
`,e+=`await _stepper.run_wait()
`,e}},{id:"turnLeftSteps",text:o(r,{id:"blocks.stepmotor.turnLeftSteps",defaultMessage:"turn [IMAGE][STEPS] steps"}),inputs:{IMAGE:{type:"image",src:p},STEPS:{type:"integer",defaultValue:10}},mpy(t){let s=this.valueToCode(t,"STEPS",this.ORDER_NONE),e="";return e+=`_stepper.move(-${s})
`,e+=`await _stepper.run_wait()
`,e}},"---",{id:"turnRight",text:o(r,{id:"blocks.stepmotor.turnRight",defaultMessage:"turn [IMAGE][DEGREES] degrees"}),inputs:{IMAGE:{type:"image",src:n},DEGREES:{type:"integer",defaultValue:15}},mpy(t){let s=this.valueToCode(t,"DEGREES",this.ORDER_NONE),e="";return e+=`_stepper.rotate(${s})
`,e+=`await _stepper.run_wait()
`,e}},{id:"turnLeft",text:o(r,{id:"blocks.stepmotor.turnLeft",defaultMessage:"trun [IMAGE][DEGREES] degrees"}),inputs:{IMAGE:{type:"image",src:p},DEGREES:{type:"integer",defaultValue:15}},mpy(t){let s=this.valueToCode(t,"DEGREES",this.ORDER_NONE),e="";return e+=`_stepper.rotate(-${s})
`,e+=`await _stepper.run_wait()
`,e}},{id:"turn",text:o(r,{id:"blocks.stepmotor.turn",defaultMessage:"turn to [ANGLE] degrees"}),inputs:{ANGLE:{type:"angle",defaultValue:0}},mpy(t){let s=this.valueToCode(t,"ANGLE",this.ORDER_NONE),e="";return e+=`_stepper.target_angle = ${s}
`,e+=`await _stepper.run_wait()
`,e}}];var i="./assets/stepper_motor-7efvczrk.py";var _=(t)=>{if(t.editor==="@blockcode/gui-arduino")return[];return[{name:"stepper_motor",type:"text/x-python",uri:i}]};var a={en:{"blocks.stepmotor.name":"28BYJ-48 Stepper","blocks.stepmotor.init":"set pins INA[INA] INB[INB] INC[INC] IND[IND]","blocks.stepmotor.rpm":"set rpm [RPM]","blocks.stepmotor.right":"turn [IMAGE] around","blocks.stepmotor.left":"turn [IMAGE] around","blocks.stepmotor.stop":"stop","blocks.stepmotor.turnRightSteps":"turn [IMAGE][STEPS] steps","blocks.stepmotor.turnLeftSteps":"turn [IMAGE][STEPS] steps","blocks.stepmotor.turnRight":"turn [IMAGE][DEGREES] degrees","blocks.stepmotor.turnLeft":"trun [IMAGE][DEGREES] degrees","blocks.stepmotor.turn":"turn to [ANGLE] degrees"},"zh-Hans":{"blocks.stepmotor.name":"28BYJ-48 步进电机","blocks.stepmotor.init":"初始引腳引脚 INA[INA] INB[INB] INC[INC] IND[IND]","blocks.stepmotor.rpm":"将转速设为[RPM]RPM","blocks.stepmotor.right":"连续右转[IMAGE]","blocks.stepmotor.left":"连续左转[IMAGE]","blocks.stepmotor.stop":"停止","blocks.stepmotor.turnRightSteps":"右转[IMAGE][STEPS]步","blocks.stepmotor.turnLeftSteps":"左转[IMAGE][STEPS]步","blocks.stepmotor.turnRight":"右转[IMAGE][DEGREES]度","blocks.stepmotor.turnLeft":"左转[IMAGE][DEGREES]度","blocks.stepmotor.turn":"转到[ANGLE]度"},"zh-Hant":{"blocks.stepmotor.name":"28BYJ-48 步進電機","blocks.stepmotor.init":"初始引腳引腳 INA[INA] INB[INB] INC[INC] IND[IND]","blocks.stepmotor.rpm":"將轉速設為[RPM]RPM","blocks.stepmotor.right":"連續右轉[IMAGE]","blocks.stepmotor.left":"連續左轉[IMAGE]","blocks.stepmotor.stop":"停止","blocks.stepmotor.turnRightSteps":"右轉[IMAGE][STEPS]步","blocks.stepmotor.turnLeftSteps":"左轉[IMAGE][STEPS]步","blocks.stepmotor.turnRight":"右轉[IMAGE][DEGREES]度","blocks.stepmotor.turnLeft":"左轉[IMAGE][DEGREES]度","blocks.stepmotor.turn":"轉到[ANGLE]度"}};var f="./assets/icon-v5jfq71g.svg";import{jsx as M}from"preact/jsx-runtime";g(a);var U={icon:f,name:M(h,{id:"blocks.stepmotor.name",defaultMessage:"28BYJ-48 Stepper"}),files:_,blocks:l};export{U as default};
