import{addLocalesMessages as b,Text as A}from"@blockcode/core";import{Text as o}from"@blockcode/core";var _="./assets/turn-left-3ncjj928.svg";var p="./assets/turn-right-ny3de90q.svg";import{jsx as n}from"preact/jsx-runtime";var i=(s)=>s.editor==="@blockcode/gui-iotbit",u=(s)=>[{id:"init",text:n(o,{id:"blocks.motor28byj48.init",defaultMessage:"set pins INA:[INA] INB:[INB] INC:[INC] IND:[IND]"}),inputs:{INA:s.boardPins?{menu:s.boardPins.out,defaultValue:i(s)?"18":"1"}:{type:"positive_integer",defaultValue:1},INB:s.boardPins?{menu:s.boardPins.out,defaultValue:i(s)?"19":"2"}:{type:"positive_integer",defaultValue:2},INC:s.boardPins?{menu:s.boardPins.out,defaultValue:i(s)?"21":"3"}:{type:"positive_integer",defaultValue:3},IND:s.boardPins?{menu:s.boardPins.out,defaultValue:i(s)?"5":"4"}:{type:"positive_integer",defaultValue:4}},mpy(e){let r=s.boardPins?e.getFieldValue("INA"):this.valueToCode(e,"INA",this.ORDER_NONE),t=s.boardPins?e.getFieldValue("INB"):this.valueToCode(e,"INB",this.ORDER_NONE),l=s.boardPins?e.getFieldValue("INC"):this.valueToCode(e,"INC",this.ORDER_NONE),a=s.boardPins?e.getFieldValue("IND"):this.valueToCode(e,"IND",this.ORDER_NONE);return this.definitions_.stepper_motor=`_stepper = stepper_motor.StepperMotor(${r}, ${t}, ${l}, ${a})`,""},ino(e){let r=s.boardPins?e.getFieldValue("INA"):this.valueToCode(e,"INA",this.ORDER_NONE),t=s.boardPins?e.getFieldValue("INB"):this.valueToCode(e,"INB",this.ORDER_NONE),l=s.boardPins?e.getFieldValue("INC"):this.valueToCode(e,"INC",this.ORDER_NONE),a=s.boardPins?e.getFieldValue("IND"):this.valueToCode(e,"IND",this.ORDER_NONE);return this.definitions_.variable_stepper_motor=`StepperMotor _stepper(${r}, ${t}, ${l}, ${a});`,""}},{id:"rpm",text:n(o,{id:"blocks.motor28byj48.rpm",defaultMessage:"set rpm [RPM]"}),inputs:{RPM:{shadow:"rpmSlider",defaultValue:10}},mpy(e){return`_stepper.rpm = ${this.valueToCode(e,"RPM",this.ORDER_NONE)}
`},ino(e){return`_stepper.setRpm(${this.valueToCode(e,"RPM",this.ORDER_NONE)});
`}},{id:"rpmSlider",shadow:!0,output:"number",inputs:{RPM:{type:"slider",defaultValue:0,min:0,max:15}},mpy(e){return[e.getFieldValue("RPM")||0,this.ORDER_NONE]},ino(e){return[e.getFieldValue("RPM")||0,this.ORDER_NONE]}},{id:"right",text:n(o,{id:"blocks.motor28byj48.right",defaultMessage:"turn [IMAGE] around"}),inputs:{IMAGE:{type:"image",src:p}},mpy(e){let r="";return r+=`_stepper.forward()
`,r+=`_stepper.run()
`,r},ino(e){return this.definitions_.loop_stepper_tick="_stepper.tick();",`_stepper.forward();
`}},{id:"left",text:n(o,{id:"blocks.motor28byj48.left",defaultMessage:"turn [IMAGE] around"}),inputs:{IMAGE:{type:"image",src:_}},mpy(e){let r="";return r+=`_stepper.backward()
`,r+=`_stepper.run()
`,r},ino(e){return this.definitions_.loop_stepper_tick="_stepper.tick();",`_stepper.backward();
`}},{id:"stop",text:n(o,{id:"blocks.motor28byj48.stop",defaultMessage:"stop"}),mpy(e){return`_stepper.stop()
`},ino(e){return`_stepper.stop();
`}},"---",{id:"turnRightSteps",text:n(o,{id:"blocks.motor28byj48.turnRightSteps",defaultMessage:"turn [IMAGE][STEPS] steps"}),inputs:{IMAGE:{type:"image",src:p},STEPS:{type:"integer",defaultValue:100}},mpy(e){let r=this.valueToCode(e,"STEPS",this.ORDER_NONE),t="";return t+=`_stepper.move(${r})
`,t+=`await _stepper.run_wait()
`,t},ino(e){let r=this.valueToCode(e,"STEPS",this.ORDER_NONE),t="";return t+=`_stepper.move(${r});
`,t+=`_stepper.runBlocking();
`,t}},{id:"turnLeftSteps",text:n(o,{id:"blocks.motor28byj48.turnLeftSteps",defaultMessage:"turn [IMAGE][STEPS] steps"}),inputs:{IMAGE:{type:"image",src:_},STEPS:{type:"integer",defaultValue:100}},mpy(e){let r=this.valueToCode(e,"STEPS",this.ORDER_NONE),t="";return t+=`_stepper.move(-${r})
`,t+=`await _stepper.run_wait()
`,t},ino(e){let r=this.valueToCode(e,"STEPS",this.ORDER_NONE),t="";return t+=`_stepper.move(-${r});
`,t+=`_stepper.runBlocking();
`,t}},"---",{id:"turnRight",text:n(o,{id:"blocks.motor28byj48.turnRight",defaultMessage:"turn [IMAGE][DEGREES] degrees"}),inputs:{IMAGE:{type:"image",src:p},DEGREES:{type:"integer",defaultValue:15}},mpy(e){let r=this.valueToCode(e,"DEGREES",this.ORDER_NONE),t="";return t+=`_stepper.rotate(${r})
`,t+=`await _stepper.run_wait()
`,t},ino(e){let r=this.valueToCode(e,"DEGREES",this.ORDER_NONE),t="";return t+=`_stepper.rotate(${r});
`,t+=`_stepper.runBlocking();
`,t}},{id:"turnLeft",text:n(o,{id:"blocks.motor28byj48.turnLeft",defaultMessage:"trun [IMAGE][DEGREES] degrees"}),inputs:{IMAGE:{type:"image",src:_},DEGREES:{type:"integer",defaultValue:15}},mpy(e){let r=this.valueToCode(e,"DEGREES",this.ORDER_NONE),t="";return t+=`_stepper.rotate(-${r})
`,t+=`await _stepper.run_wait()
`,t},ino(e){let r=this.valueToCode(e,"DEGREES",this.ORDER_NONE),t="";return t+=`_stepper.rotate(-${r});
`,t+=`_stepper.runBlocking();
`,t}},{id:"turn",text:n(o,{id:"blocks.motor28byj48.turn",defaultMessage:"turn to [ANGLE] degrees"}),inputs:{ANGLE:{type:"integer",defaultValue:0}},mpy(e){let r=this.valueToCode(e,"ANGLE",this.ORDER_NONE),t="";return t+=`_stepper.target_angle = ${r}
`,t+=`await _stepper.run_wait()
`,t},ino(e){let r=this.valueToCode(e,"ANGLE",this.ORDER_NONE),t="";return t+=`_stepper.setTargetAngle(${r});
`,t+=`_stepper.runBlocking();
`,t}}];var d="./assets/stepper_motor-80vwk46z.py";var c="./assets/stepper_motor-kz19hkab.h";var f="./assets/stepper_motor-52rk6qjq.cpp";var g=(s)=>{if(s.editor==="@blockcode/gui-arduino")return[{header:!0,name:"stepper_motor.h",type:"text/x-c",uri:c},{name:"stepper_motor.cpp",type:"text/x-c",uri:f}];return[{name:"stepper_motor",type:"text/x-python",uri:d}]};var E={en:{"blocks.motor28byj48.name":"28BYJ-48 Stepper","blocks.motor28byj48.init":"set pins INA:[INA] INB:[INB] INC:[INC] IND:[IND]","blocks.motor28byj48.rpm":"set rpm [RPM]","blocks.motor28byj48.right":"turn [IMAGE] around","blocks.motor28byj48.left":"turn [IMAGE] around","blocks.motor28byj48.stop":"stop","blocks.motor28byj48.turnRightSteps":"turn [IMAGE][STEPS] steps","blocks.motor28byj48.turnLeftSteps":"turn [IMAGE][STEPS] steps","blocks.motor28byj48.turnRight":"turn [IMAGE][DEGREES] degrees","blocks.motor28byj48.turnLeft":"trun [IMAGE][DEGREES] degrees","blocks.motor28byj48.turn":"turn to [ANGLE] degrees"},"zh-Hans":{"blocks.motor28byj48.name":"28BYJ-48 步进电机","blocks.motor28byj48.init":"初始引脚 INA:[INA] INB:[INB] INC:[INC] IND:[IND]","blocks.motor28byj48.rpm":"将转速设为[RPM]RPM","blocks.motor28byj48.right":"连续右转[IMAGE]","blocks.motor28byj48.left":"连续左转[IMAGE]","blocks.motor28byj48.stop":"停止","blocks.motor28byj48.turnRightSteps":"右转[IMAGE][STEPS]步","blocks.motor28byj48.turnLeftSteps":"左转[IMAGE][STEPS]步","blocks.motor28byj48.turnRight":"右转[IMAGE][DEGREES]度","blocks.motor28byj48.turnLeft":"左转[IMAGE][DEGREES]度","blocks.motor28byj48.turn":"转到[ANGLE]度"},"zh-Hant":{"blocks.motor28byj48.name":"28BYJ-48 步進電機","blocks.motor28byj48.init":"初始引腳 INA:[INA] INB:[INB] INC:[INC] IND:[IND]","blocks.motor28byj48.rpm":"將轉速設為[RPM]RPM","blocks.motor28byj48.right":"連續右轉[IMAGE]","blocks.motor28byj48.left":"連續左轉[IMAGE]","blocks.motor28byj48.stop":"停止","blocks.motor28byj48.turnRightSteps":"右轉[IMAGE][STEPS]步","blocks.motor28byj48.turnLeftSteps":"左轉[IMAGE][STEPS]步","blocks.motor28byj48.turnRight":"右轉[IMAGE][DEGREES]度","blocks.motor28byj48.turnLeft":"左轉[IMAGE][DEGREES]度","blocks.motor28byj48.turn":"轉到[ANGLE]度"}};var C="./assets/icon-v5jfq71g.svg";import{jsx as h}from"preact/jsx-runtime";b(E);var J={icon:C,name:h(A,{id:"blocks.motor28byj48.name",defaultMessage:"28BYJ-48 Stepper"}),files:g,blocks:u};export{J as default};
