import{addLocalesMessages as u,Text as g}from"@blockcode/core";import{Text as a}from"@blockcode/core";import{jsx as s}from"preact/jsx-runtime";var o=[{id:"whenReceived",text:s(a,{id:"blocks.broadcast.whenReceived",defaultMessage:"when I receive message"}),hat:!0,mpy(e){let t=this.statementToCode(e);t=this.addEventTrap(t,e.id),t=t.replace(`():
`,`(target):
`);let d="";return d+=`@broadcast.when_received("default", target)
`,d+=t,d}},{id:"send",text:s(a,{id:"blocks.broadcast.send",defaultMessage:"broadcast message [MESSAGE]"}),inputs:{MESSAGE:{type:"text",defaultValue:s(a,{id:"blocks.broadcast.message",defaultMessage:"hello"})}},mpy(e){return`broadcast.send(str(${(this.valueToCode(e,"MESSAGE",this.ORDER_NONE)||'""').replace(":","_")}))
`}},{id:"received",text:s(a,{id:"blocks.broadcast.received",defaultMessage:"received message"}),output:"string",mpy(e){return[`broadcast.get_message()
`,this.ORDER_FUNCTION_CALL]}},"---",{id:"whenReceivedNamed",text:s(a,{id:"blocks.broadcast.whenReceivedNamed",defaultMessage:"when I receive named [NAME] message"}),hat:!0,inputs:{NAME:{type:"text",defaultValue:s(a,{id:"blocks.broadcast.messageName",defaultMessage:"my"})}},mpy(e){let t=this.valueToCode(e,"NAME",this.ORDER_NONE),d=this.statementToCode(e);d=this.addEventTrap(d,e.id),d=d.replace(`():
`,`(target):
`);let r="";return r+=`@broadcast.when_received(${t}, target)
`,r+=d,r}},{id:"sendName",text:s(a,{id:"blocks.broadcast.sendName",defaultMessage:"broadcast named [NAME] message [MESSAGE]"}),inputs:{NAME:{type:"text",defaultValue:s(a,{id:"blocks.broadcast.messageName",defaultMessage:"say"})},MESSAGE:{type:"text",defaultValue:s(a,{id:"blocks.broadcast.message",defaultMessage:"hello"})}},mpy(e){let t=this.valueToCode(e,"NAME",this.ORDER_NONE)||'"default"';return`broadcast.send(str(${this.valueToCode(e,"MESSAGE",this.ORDER_NONE)||'""'}), name=str(${t}))
`}},{id:"receivedNamed",text:s(a,{id:"blocks.broadcast.receivedNamed",defaultMessage:"received named [NAME] message"}),output:"string",inputs:{NAME:{type:"text",defaultValue:s(a,{id:"blocks.broadcast.messageName",defaultMessage:"say"})}},mpy(e){return[`broadcast.get_message(str(${this.valueToCode(e,"NAME",this.ORDER_NONE)||'"default"'}))
`,this.ORDER_FUNCTION_CALL]}},"---",{id:"receivedIndex",text:s(a,{id:"blocks.broadcast.receivedIndex",defaultMessage:"received message [INDEX]"}),inputs:{INDEX:{menu:"receivedParam"}},output:"string",mpy(e){return[`broadcast.get_message_info(str(${this.quote_(e.getFieldValue("INDEX"))||'"timestamp"'}))
`,this.ORDER_FUNCTION_CALL]}},{id:"receivedNamedIndex",text:s(a,{id:"blocks.broadcast.receivedNameIndex",defaultMessage:"received named [NAME] message [INDEX]"}),inputs:{NAME:{type:"text",defaultValue:s(a,{id:"blocks.broadcast.messageName",defaultMessage:"say"})},INDEX:{menu:"receivedParam"}},output:"string",mpy(e){let t=this.valueToCode(e,"NAME",this.ORDER_NONE)||'"default"';return[`broadcast.get_message_info(str(${this.quote_(e.getFieldValue("INDEX"))||'"timestamp"'}), name=str(${t}))
`,this.ORDER_FUNCTION_CALL]}},"---",{id:"setGroup",text:s(a,{id:"blocks.broadcast.setGroup",defaultMessage:"set broadcast group [ID]"}),inputs:{ID:{type:"string",defaultValue:"1"}},mpy(e){return`broadcast.set_group(str(${this.valueToCode(e,"ID",this.ORDER_NONE)||"1"}))
`}}],c={receivedParam:{type:"string",items:[[s(a,{id:"blocks.broadcast.receivedTime",defaultMessage:"timestamp"}),"timestamp"],[s(a,{id:"blocks.broadcast.receivedSerial",defaultMessage:"serial number"}),"serialnumber"],[s(a,{id:"blocks.broadcast.receivedMac",defaultMessage:"mac"}),"mac"]]}};var i={en:{"blocks.broadcast.name":"Broadcast","blocks.broadcast.setGroup":"set broadcast group [ID]","blocks.broadcast.send":"broadcast message [MESSAGE]","blocks.broadcast.sendName":"broadcast label [NAME] message [MESSAGE]","blocks.broadcast.whenReceived":"when I receive message","blocks.broadcast.whenReceivedNamed":"when I receive label [NAME] message","blocks.broadcast.message":"hello","blocks.broadcast.messageName":"say","blocks.broadcast.received":"received message","blocks.broadcast.receivedNamed":"received label [NAME] message","blocks.broadcast.receivedIndex":"received message [INDEX]","blocks.broadcast.receivedNameIndex":"received label [NAME] message [INDEX]","blocks.broadcast.receivedMac":"mac address","blocks.broadcast.receivedTime":"timestamp","blocks.broadcast.receivedSerial":"serial number"},"zh-Hans":{"blocks.broadcast.name":"无线广播","blocks.broadcast.setGroup":"将广播组设为 [ID]","blocks.broadcast.send":"广播消息 [MESSAGE]","blocks.broadcast.sendName":"广播主题为 [NAME] 的 [MESSAGE] 消息","blocks.broadcast.whenReceived":"当接收到消息","blocks.broadcast.whenReceivedNamed":"当接收到主题为 [NAME] 的消息","blocks.broadcast.message":"你好","blocks.broadcast.messageName":"问候","blocks.broadcast.received":"消息","blocks.broadcast.receivedNamed":"主题为 [NAME] 的消息","blocks.broadcast.receivedIndex":"消息的 [INDEX]","blocks.broadcast.receivedNameIndex":"主题为 [NAME] 的消息的 [INDEX]","blocks.broadcast.receivedMac":"MAC 地址","blocks.broadcast.receivedTime":"时间戳","blocks.broadcast.receivedSerial":"序列号"},"zh-Hant":{"blocks.broadcast.name":"無線廣播","blocks.broadcast.setGroup":"將廣播組設為 [ID]","blocks.broadcast.send":"廣播消息 [MESSAGE]","blocks.broadcast.sendName":"廣播名為 [NAME] 的 [MESSAGE] 消息","blocks.broadcast.whenReceived":"當接收到消息","blocks.broadcast.whenReceivedNamed":"當接收到名為 [NAME] 的消息","blocks.broadcast.message":"你好","blocks.broadcast.messageName":"問候","blocks.broadcast.received":"消息","blocks.broadcast.receivedNamed":"名為 [NAME] 的消息","blocks.broadcast.receivedIndex":"消息的 [INDEX]","blocks.broadcast.receivedNameIndex":"名為 [NAME] 消息的 [INDEX]","blocks.broadcast.receivedMac":"MAC 地址","blocks.broadcast.receivedTime":"時間戳","blocks.broadcast.receivedSerial":"序列號"}};var n="./assets/icon-em6p3nz5.png";var m="./assets/broadcast-88k09zyq.py";import{jsx as E}from"preact/jsx-runtime";u(i);var S={icon:n,name:E(g,{id:"blocks.broadcast.name",defaultMessage:"Broadcast"}),files:[{name:"broadcast",type:"text/x-python",uri:m}],blocks:o,menus:c};export{S as default};
