import{addLocalesMessages as x,Text as _}from"@blockcode/core";import{Text as d}from"@blockcode/core";import{jsx as r}from"preact/jsx-runtime";var c=(n)=>[{id:"init",text:r(d,{id:"blocks.aivoxassistant.init",defaultMessage:"set pins RX:[RX] TX:[TX]"}),inputs:{RX:n.boardPins?{menu:n.boardPins.all}:{type:"positive_integer",defaultValue:2},TX:n.boardPins?{menu:n.boardPins.all}:{type:"positive_integer",defaultValue:3}},ino(t){let i=n.boardPins?t.getFieldValue("RX"):this.valueToCode(t,"RX",this.ORDER_NONE),a=n.boardPins?t.getFieldValue("TX"):this.valueToCode(t,"TX",this.ORDER_NONE);return this.definitions_.include_regexp="#include <Regexp.h>",this.definitions_.include_softwareserial="#include <SoftwareSerial.h>",this.definitions_.variable_aivoxAssistant=`SoftwareSerial aivoxAssistant(${i}, ${a});`,this.definitions_.setup_aivoxAssistant="aivoxAssistant.begin(115200);",""}},"---",{id:"whenCommand",text:r(d,{id:"blocks.aivoxassistant.whenCommand",defaultMessage:"when receive [CMD] command"}),hat:!0,inputs:{CMD:{type:"string",defaultValue:"turn on led"}},ino(t){if(this.definitions_.variable_commandReg="MatchState cmdRe;",!this.definitions_.processAssistant){let e="";e+=`void processAssistant() {
`,e+=`  if (aivoxAssistant.available() == 0) return;
`,e+=`  String cmd = aivoxAssistant.readStringUntil('\\n');
`,e+=`  cmdRe.Target(cmd.c_str());
`,e+="}",this.definitions_.processAssistant=e,this.definitions_.declare_processAssistant="void processAssistant();",this.definitions_.loop_processAssistant="processAssistant();"}let i=this.createName("assistantCommand"),a=this.statementToCode(t)||"";this.definitions_[`declare_${i}`]=`void ${i}();`,this.definitions_[i]=`void ${i}() {
${a}}`;let s=this.valueToCode(t,"CMD",this.ORDER_NONE).replace(/\{\S+\}/g,"(%S+)").replace(/\s+/g,"%s+");this.definitions_.processAssistant=this.definitions_.processAssistant.replace(`;
}`,`;
  if (cmdRe.Match(${s}) > 0) return ${i}();
}`)}},{id:"argument",text:r(d,{id:"blocks.aivoxassistant.argument",defaultMessage:"argument [ARG] of command"}),output:"string",inputs:{ARG:{type:"string",defaultValue:"x"}},ino(t){let i=this.valueToCode(t,"ARG",this.ORDER_NONE),a=t.getRootBlock(),l=this.valueToCode(a,"CMD",this.ORDER_NONE),s="";s+=`String getCommandArgument(uint8_t idx) {
`,s+=`  char arg[100];
`,s+=`  cmdRe.GetCapture(arg, idx);
`,s+=`  return String(arg);
`,s+="}",this.definitions_.getCommandArgument=s,this.definitions_.declare_getCommandArgument="String getCommandArgument(uint8_t idx);";let e=0,m=[...l.matchAll(/\{(\w+)\}/g)];for(let o=0;o<m.length;o++)if(m[o][1]===i){e=o;break}return s=`getCommandArgument(${e})`,[s]}}];var u="///docs.emakefun.com/#/zh-cn/ph2.0_sensors/smart_module/ai_voice_assistant/ai_voice_assistant";var g={en:{"blocks.aivoxassistant.name":"AI Vox Assistant","blocks.aivoxassistant.init":"set pins RX:[RX] TX:[TX]","blocks.aivoxassistant.whenCommand":"when receive [CMD] command","blocks.aivoxassistant.argument":"argument [ARG] of command"},"zh-Hans":{"blocks.aivoxassistant.name":"AI 语音助手","blocks.aivoxassistant.init":"初始引脚 RX:[RX] TX:[TX]","blocks.aivoxassistant.whenCommand":"当收到 [CMD] 指令时","blocks.aivoxassistant.argument":"指令参数 [ARG]"},"zh-Hant":{"blocks.aivoxassistant.name":"AI 語音助手","blocks.aivoxassistant.init":"初始引腳 RX:[RX] TX:[TX]","blocks.aivoxassistant.whenCommand":"當收到 [CMD] 指令時","blocks.aivoxassistant.argument":"指令參數 [ARG]"}};var h="./assets/icon-jep655t2.svg";import{jsx as C}from"preact/jsx-runtime";x(g);var E={icon:h,name:C(_,{id:"blocks.aivoxassistant.name",defaultMessage:"AI Vox Assistant"}),blocks:c,readme:u};export{E as default};
