en:
  blocks.firmata.name: Arduino Firmata
  blocks.firmata.blockA: block [KEY]
  blocks.firmata.connect: block

zh-Hans:
  blocks.firmata.name: Arduino Firmata
  blocks.firmata.blockA: 积木 [KEY]
  blocks.firmata.connect: 连接

zh-Hant:
  blocks.firmata.name: Arduino Firmata
  blocks.firmata.blockA: 積木 [KEY]
  blocks.firmata.connect: 连接
