en:
  blocks.firmata.name: Arduino Firmata
  blocks.firmata.blockA: block [KEY]
  blocks.firmata.connect: block
  blocks.firmata.readAnalog: read analog [PIN] value
  blocks.firmata.readDigital: read digital [PIN] value
  blocks.firmata.readDistance: read Distance [PIN] value
  blocks.firmata.readTemp: read temperature [PIN] value
  blocks.firmata.readHum: read humidity [PIN] value
  blocks.firmata.setPWM: set PWM [PIN] value [VALUE]
  blocks.firmata.setDigital: set digital [PIN] value [VALUE]
  blocks.firmata.high: high
  blocks.firmata.low: low

zh-Hans:
  blocks.firmata.name: Arduino Firmata
  blocks.firmata.blockA: 积木 [KEY]
  blocks.firmata.connect: 连接
  blocks.firmata.readAnalog: 读取模拟口 [PIN] 值
  blocks.firmata.readDigital: 读取数字口 [PIN] 值
  blocks.firmata.readDistance: 距离传感器 [PIN] 检测到的距离
  blocks.firmata.readTemp: 读取温度传感器 [PIN] 的温度值
  blocks.firmata.readHum: 读取湿度传感器 [PIN] 的湿度值
  blocks.firmata.setPWM: 设置PWM接口 [PIN] 值为 [VALUE]
  blocks.firmata.setDigital: 设置数字接口 [PIN] 电平状态为 [VALUE]
  blocks.firmata.high: 高
  blocks.firmata.low: 低

zh-Hant:
  blocks.firmata.name: Arduino Firmata
  blocks.firmata.blockA: 積木 [KEY]
  blocks.firmata.connect: 连接
  blocks.firmata.readAnalog: 读取模拟口 [PIN] 值
  blocks.firmata.readDigital: 读取数字口 [PIN] 值
  blocks.firmata.readDistance: 距离传感器 [PIN] 检测到的距离
  blocks.firmata.readTemp: 读取温度传感器 [PIN] 的温度值
  blocks.firmata.readHum: 读取湿度传感器 [PIN] 的湿度值
  blocks.firmata.setPWM: 设置PWM接口 [PIN] 值为 [VALUE]
  blocks.firmata.setDigital: 设置数字接口 [PIN] 电平状态为 [VALUE]
  blocks.firmata.high: 高
  blocks.firmata.low: 低