import{addLocalesMessages as N,Text as c}from"@blockcode/core";import{Text as l}from"@blockcode/core";import{jsx as n}from"preact/jsx-runtime";var u=(y)=>[{id:"initDisplay",text:n(l,{id:"blocks.oled.initDisplay",defaultMessage:"set oled [DRIVER] display [SIZE]"})},"---",{id:"drawText",text:n(l,{id:"blocks.oled.drawText",defaultMessage:"display text [TEXT] at x:[X] y:[Y]"}),inputs:{TEXT:{type:"string",defaultValue:"hello"},X:{type:"integer",defaultValue:0},Y:{type:"integer",defaultValue:0}},mpy(e){let t=this.valueToCode(e,"TEXT",this.ORDER_NONE),i=this.valueToCode(e,"X",this.ORDER_NONE),s=this.valueToCode(e,"Y",this.ORDER_NONE),o=`display.write(f"{${t}}", ${i}, ${s})
`,a=e.getNextBlock();if(a&&a.type.search(/_display[\w]+$/)!==-1)return o;return o+=`display.show()
`,o},emu(e){let t=this.valueToCode(e,"TEXT",this.ORDER_NONE)||'""',i=this.valueToCode(e,"X",this.ORDER_NONE),s=this.valueToCode(e,"Y",this.ORDER_NONE);return`runtime.drawText(\`\${${t}}\`, ${i}, ${s});
`}},{id:"drawTextLine",text:n(l,{id:"blocks.oled.drawTextLine",defaultMessage:"display text [TEXT] at line [LINE]"}),inputs:{TEXT:{type:"string",defaultValue:"hello world"},LINE:{menu:[1,2,3,4,5]}},mpy(e){let t=this.valueToCode(e,"TEXT",this.ORDER_NONE),i=parseInt(e.getFieldValue("LINE"))-1,s=`display.write(f"{${t}}", 2, ${i*13}, wrap=True)
`,o=e.getNextBlock();if(o&&o.type.search(/_display[\w]+$/)!==-1)return s;return s+=`display.show()
`,s},emu(e){let t=this.valueToCode(e,"TEXT",this.ORDER_NONE)||'""',i=parseInt(e.getFieldValue("LINE"))-1;return`runtime.drawTextLine(\`\${${t}}\`, ${i});
`}},{id:"clearDisplay",text:n(l,{id:"blocks.oled.clearDisplay",defaultMessage:"clear display"}),mpy(e){let t=`display.fill(0)
`,i=e.getNextBlock();if(i&&i.type.search(/_display[\w]+$/)!==-1)return t;return t+=`display.show()
`,t},emu(e){return`runtime.clearScreen();
`}},"---",{id:"drawPixel",text:n(l,{id:"blocks.oled.drawPixel",defaultMessage:"draw pixel x:[X] y:[Y]"}),inputs:{X:{type:"integer",defaultValue:10},Y:{type:"integer",defaultValue:10}},mpy(e){let t=this.valueToCode(e,"X",this.ORDER_NONE),i=this.valueToCode(e,"Y",this.ORDER_NONE),s=`display.pixel(${t}, ${i}, 1)
`,o=e.getNextBlock();if(o&&o.type.search(/_display[\w]+$/)!==-1)return s;return s+=`display.show()
`,s},emu(e){let t=this.valueToCode(e,"X",this.ORDER_NONE),i=this.valueToCode(e,"Y",this.ORDER_NONE);return`runtime.drawPixel(${t}, ${i});
`}},{id:"drawLine",text:n(l,{id:"blocks.oled.drawLine",defaultMessage:"draw line from x1:[X1] y1:[Y1] to x2:[X2] y2:[Y2]"}),inputs:{X1:{type:"integer",defaultValue:0},Y1:{type:"integer",defaultValue:0},X2:{type:"integer",defaultValue:20},Y2:{type:"integer",defaultValue:20}},mpy(e){let t=this.valueToCode(e,"X1",this.ORDER_NONE),i=this.valueToCode(e,"Y1",this.ORDER_NONE),s=this.valueToCode(e,"X2",this.ORDER_NONE),o=this.valueToCode(e,"Y2",this.ORDER_NONE),a=`display.line(${t}, ${i}, ${s}, ${o})
`,d=e.getNextBlock();if(d&&d.type.search(/_display[\w]+$/)!==-1)return a;return a+=`display.show()
`,a},emu(e){let t=this.valueToCode(e,"X1",this.ORDER_NONE),i=this.valueToCode(e,"Y1",this.ORDER_NONE),s=this.valueToCode(e,"X2",this.ORDER_NONE),o=this.valueToCode(e,"Y2",this.ORDER_NONE);return`runtime.drawLine(${t}, ${i}, ${s}, ${o});
`}},{id:"drawEllipse",text:n(l,{id:"blocks.oled.drawEllipse",defaultMessage:"draw ellipse with x-radius:[RX] and y-radius:[RY] at x:[X] y:[Y]"}),inputs:{RX:{type:"positive_integer",defaultValue:20},RY:{type:"positive_integer",defaultValue:10},X:{type:"integer",defaultValue:0},Y:{type:"integer",defaultValue:0}},mpy(e){let t=this.valueToCode(e,"RX",this.ORDER_NONE),i=this.valueToCode(e,"RY",this.ORDER_NONE),s=this.valueToCode(e,"X",this.ORDER_NONE),o=this.valueToCode(e,"Y",this.ORDER_NONE),a=`display.ellipse(${s}, ${o}, ${t}, ${i})
`,d=e.getNextBlock();if(d&&d.type.search(/_display[\w]+$/)!==-1)return a;return a+=`display.show()
`,a},emu(e){let t=this.valueToCode(e,"RX",this.ORDER_NONE),i=this.valueToCode(e,"RY",this.ORDER_NONE),s=this.valueToCode(e,"X",this.ORDER_NONE),o=this.valueToCode(e,"Y",this.ORDER_NONE);return`runtime.drawEllipse(${s}, ${o}, ${t}, ${i});
`}},{id:"drawRect",text:n(l,{id:"blocks.oled.drawRect",defaultMessage:"draw rect with width:[WIDTH] height:[HEIGHT] at x:[X] y:[Y]"}),inputs:{WIDTH:{type:"positive_integer",defaultValue:20},HEIGHT:{type:"positive_integer",defaultValue:10},X:{type:"integer",defaultValue:0},Y:{type:"integer",defaultValue:0}},mpy(e){let t=this.valueToCode(e,"WIDTH",this.ORDER_NONE),i=this.valueToCode(e,"HEIGHT",this.ORDER_NONE),s=this.valueToCode(e,"X",this.ORDER_NONE),o=this.valueToCode(e,"Y",this.ORDER_NONE),a=`display.rect(${s}, ${o}, ${t}, ${i})
`,d=e.getNextBlock();if(d&&d.type.search(/_display[\w]+$/)!==-1)return a;return a+=`display.show()
`,a},emu(e){let t=this.valueToCode(e,"WIDTH",this.ORDER_NONE),i=this.valueToCode(e,"HEIGHT",this.ORDER_NONE),s=this.valueToCode(e,"X",this.ORDER_NONE),o=this.valueToCode(e,"Y",this.ORDER_NONE);return`runtime.drawRect(${s}, ${o}, ${t}, ${i});
`}},{id:"fillRect",text:n(l,{id:"blocks.oled.fillRect",defaultMessage:"fill rect with width:[WIDTH] height:[HEIGHT] at x:[X] y:[Y]"}),inputs:{WIDTH:{type:"positive_integer",defaultValue:20},HEIGHT:{type:"positive_integer",defaultValue:10},X:{type:"integer",defaultValue:0},Y:{type:"integer",defaultValue:0}},mpy(e){let t=this.valueToCode(e,"WIDTH",this.ORDER_NONE),i=this.valueToCode(e,"HEIGHT",this.ORDER_NONE),s=this.valueToCode(e,"X",this.ORDER_NONE),o=this.valueToCode(e,"Y",this.ORDER_NONE),a=`display.fill_rect(${s}, ${o}, ${t}, ${i})
`,d=e.getNextBlock();if(d&&d.type.search(/_display[\w]+$/)!==-1)return a;return a+=`display.show()
`,a},emu(e){let t=this.valueToCode(e,"WIDTH",this.ORDER_NONE),i=this.valueToCode(e,"HEIGHT",this.ORDER_NONE),s=this.valueToCode(e,"X",this.ORDER_NONE),o=this.valueToCode(e,"Y",this.ORDER_NONE);return`runtime.fillRect(${s}, ${o}, ${t}, ${i});
`}}];var r={en:{"blocks.oled.name":"OLED"},"zh-Hans":{"blocks.oled.name":"OLED"},"zh-Hant":{"blocks.oled.name":"OLED"}};var h="./assets/icon-7mgxv3je.png";import{jsx as p}from"preact/jsx-runtime";N(r);var g={icon:h,name:p(c,{id:"blocks.oled.name",defaultMessage:"OLED"}),blocks:u};export{g as default};
